.travis.yml, CHANGELOG.md, README.md, data.tf, examples/eks_test_fixture/main.tf, local.tf, main.tf, outputs.tf, variables.tf, workers.tf
* As a module consumer, I would like to supply some userdata for instances to run on boot. - done
* As a module maintainer, I have a strong dislike for hcl with various languages embedded. Separate these out into template files to be rendered. - done
* CI now skips final step which will fail until upstream fixes
=> byo userdata now enabled. refactor some parts into dedicated templates for maintainability

CHANGELOG.md, README.md, examples/eks_test_fixture/main.tf, main.tf, variables.tf
As a consumer of the module, I want to have kubectl configured to use the cluster automatically.
Variables have been added to support outputting of config files and automatic configuration of kubectl for thecurrent shell session.
=> kubectl now configurable by the module

README.md, outputs.tf
Added output for IAM role name that is automatically created for all workers within AutoScallingGoup.
That would allow granting additional permissions for the worker nodes, like using S3 buckets etc.
=> Add IAM role output

examples/eks_test_fixture/README.md
Fixed missing service type in the IAM policy for testing.
Using this policy (before fixing) resulted with the error:
`MalformedPolicyDocument: Actions/Conditions must be prefaced by a vendor, e.g., i
am, sdb, ec2, etc.`
=> Fix typo in IAM policy for testing

data.tf
Fix error when using IPv6.
e.g.
(My IPv6 address is masked.)
```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
data.http.workstation_external_ip: Refreshing state...
data.aws_region.current: Refreshing state...
data.aws_iam_policy_document.cluster_assume_role_policy: Refreshing state...
data.aws_iam_policy_document.workers_assume_role_policy: Refreshing state...
data.aws_ami.eks_worker: Refreshing state...
------------------------------------------------------------------------
Error: Error running plan: 1 error(s) occurred:
* module.eks.aws_security_group_rule.cluster_https_cidr_ingress: "cidr_blocks.0" must contain a valid network CIDR, got …
```
=> Fix error when using IPv6

README.md
Copy/pasting the example is not working out of the box. It might take some time to notice the version difference.
=> Bump module version in usage example

README.md, data.tf, kubectl.tf, local.tf, templates/kubeconfig.tpl, variables.tf
Here I am addressing 2 problems:
1. The strings used in the generated `kubeconfig` file are non-informative and non-unique. This makes merging with existing config a pain and when more than a single EKS cluster is managed by TF, manual changes are required.
2. The path of the generated `kubeconfig` file is not unique. This also makes managing multiple clusters in TF impossible as they will write to the same file. Having multiple clusters in TF is very likely as in place version upgrades of EKS are currently not supported so upgrading to a new version of k8s will mean running 2 clusters side by side for some amount of time.
Both of these have been discussed in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/49 and https://github.com/terraform-aws-modules/terraform-aws-eks/is …
=> Making kubeconfig file path and generated config unique

CHANGELOG.md, README.md, outputs.tf
Just a small, but useful addition that will allow using worker's IAM role in policy documents (having only role name in outputs is apparently not enough in some cases)
=> Worker iam role arn

.gitignore, CHANGELOG.md, README.md, aws_auth.tf, data.tf, examples/eks_test_fixture/main.tf, examples/eks_test_fixture/variables.tf, templates/config-map-aws-auth-map_accounts.yaml.tpl, templates/config-map-aws-auth-map_roles.yaml.tpl, templates/config-map-aws-auth-map_users.yaml.tpl, templates/config-map-aws-auth.yaml.tpl, variables.tf
Related issue: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/50
The problem: Any users, roles or accounts that need access to the EKS cluster must have the relevant entries in the `aws-auth` configmap inside k8s. Currently this module only puts the ARN of the worker group in there, thus forcing people to manage this file manually, which is a pain.
Limitations:
1. It's a bit of a mess due to needing to loop over values in a template. Not sure if the new template syntax in [0.12](https://www.hashicorp.com/blog/terraform-0-1-2-preview) will help. Let me know if there's a better way to do this!
2. We can't have multiple groups per user or role due to this error: `lookup() may only be used with flat maps, this map contains elements of type list in`. No big deal I think at …
=> Fully manage aws-auth configmap file

variables.tf, workers.tf
Adds a `subnets` option to `worker_groups`. The primary use-case is to address #15 . This will allow the eks cluster to be passed both private and public subnets while the workers only run in the private subnets.
Thanks!
=> Optionally define worker subnets

CHANGELOG.md, README.md, outputs.tf
`workers_asg_names`, a counterpart to `workers_asg_arns`, was added to outputs. Fixes https://github.com/terraform-aws-modules/terraform-aws-eks/issues/76
=> add workers_asg_names to outputs

CHANGELOG.md, README.md, data.tf, examples/eks_test_fixture/main.tf, variables.tf, workers.tf
`length(var.worker_groups)` has been replaced by a top-level variable `worker_group_length` as `length` of a computed value cannot be used. This fixes https://github.com/terraform-aws-modules/terraform-aws-eks/issues/73
Breaking Changes:
`worker_group_length` must be specified to use more than one worker group.
=> Use static not computed worker group count

CHANGELOG.md, README.md, cluster.tf, data.tf, local.tf, main.tf, variables.tf
This PR removes the HTTP callout and security rule logic for master security group. Access to the Kubernetes masters cannot be restricted, nor does it need granting. As mentioned on https://github.com/terraform-aws-modules/terraform-aws-eks/pull/69#issuecomment-406123233
Breaking change for some users: This removes the, now redundant, `workstation_cidr` variable.
=> No http callout

CHANGELOG.md, variables.tf, workers.tf
Just add `spot_price` option to aws_launch_configuration and variable`update workers_group_defaults` for default spot value(on-demand, if spot_price is empty).
Firstly issue rised with #72
=> add spot_price option to aws_launch_configuration

variables.tf
I think as a default, 20GB is way too low. For example, GKE uses 100GB.
=> Setting worker default volume size to 100GB

variables.tf
Very important change to remove an extra space from a comment.  You're welcome world!
=> fix comment alignment on workers_group_defaults

CHANGELOG.md, variables.tf, workers.tf
Add option to disable [enhanced monitoring](https://www.terraform.io/docs/providers/aws/r/launch_configuration.html#enable_monitoring) on the workers
=> add option to disable enhanced monitoring on workers

CHANGELOG.md, local.tf
AWS announced [1] new t3 instance types, this PR adds the necessary configuration to use them. 
[1] https://aws.amazon.com/blogs/aws/new-t3-instances-burstable-cost-effective-performance/
=> add t3 instance type settings

variables.tf
Fix typo with node-labels in comment
=> Fix typo with --node-labels

examples/eks_test_fixture/main.tf
This is a fix for #104 . Passing public and private subnets to terraform-aws-eks causes nodes to end up as public or private at random. 
In current EKS implementation this works, as the magic `kubernetes.io/cluster/${local.cluster_name} = shared` tag is set on public subnets by the VPC module. This allows kubernetes to correctly create public ELBs.
=> Example: remove public subnets from eks module call

.gitignore, CHANGELOG.md, data.tf, local.tf, templates/userdata.sh.tpl
Add support for the new amazon-eks-node-* AMI.  Fix https://github.com/terraform-aws-modules/terraform-aws-eks/issues/97
=> Add support for the new amazon-eks-node-* AMI

CHANGELOG.md, workers.tf
Allow a custom AMI to be specified as a default, instead of having to do it per worker group. This should also fix https://github.com/terraform-aws-modules/terraform-aws-eks/issues/85, which was closed without a fix (only a workaround).
=> Allow a custom AMI to be specified as a default

CHANGELOG.md, local.tf, workers.tf
Passing `subnets` in `var.workers_group_defaults` is currently not doing anything.
=> Fix default worker subnets not working

CHANGELOG.md, workers.tf
A fix for `autoscaling_enabled` in `var.workers_group_defaults` not doing anything.
=> Fix default worker autoscaling_enabled not working

CHANGELOG.md, README.md, aws_auth.tf, local.tf, outputs.tf, templates/config-map-aws-auth.yaml.tpl, templates/worker-role.tpl, variables.tf, workers.tf
-resolves #136 
-added `iam_role_id` to the worker group config
=> allow specifying an IAM role for each worker group

CHANGELOG.md, README.md, data.tf, examples/eks_test_fixture/main.tf, main.tf, workers.tf
Cosmetic syntax changes to improve readability. Credit goes to @strygin for the inspiration.
2 changes:
- Remove lookup function when no default is required to just refer to the map and key like this `map["key"]`. This reduces the `()` which improves readability.
- Where possible, use an actual map instead of using the map function. e.g. `{key = "value"}`
=> Cosmetic fixes

workers.tf
I think I made this mistake in my rebase of https://github.com/terraform-aws-modules/terraform-aws-eks/pull/131. I was using a new UI tool for interactive rebase 🤨
=> Fix for ERROR: 'aws_iam_instance_profile.workers' not found

CHANGELOG.md, README.md, cluster.tf, variables.tf, workers.tf
Added timeout configs to the `aws_eks_cluster` resource.
I set the timeouts to 1m to test for failure (could not test timeout for more than default time since it is unpredictable when it would happen). Here are the results:
```
1 error(s) occurred:
TestEKS 2018-10-02T12:32:30-04:00 command.go:100: 
TestEKS 2018-10-02T12:32:30-04:00 command.go:100: * module.test_eks_module.module.eks.aws_eks_cluster.this: 1 error(s) occurred:
TestEKS 2018-10-02T12:32:30-04:00 command.go:100: 
TestEKS 2018-10-02T12:32:30-04:00 command.go:100: * aws_eks_cluster.this: timeout while waiting for state to become 'ACTIVE' (last state: 'CREATING', timeout: 1m0s)
```
I tried to update `README.md` using `terraform-docs` and the given lines of code, but that ended up erasing the whole file for me. So I added in the …
=> Added timeout configs and variables to aws_eks_cluster resource

aws_auth.tf, local.tf
Fixed issue with workers_group_defaults_defaults.iam_role_id and added explicit depends_on for 'update_config_map_aws_auth'
Minimal fixes for this issue:
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/146
This PR only attempts to fix the minimal requirements of the issue.
- `update_config_map_aws_auth` null resource now depends on `aws_eks_cluster.this` 
- `iam_role_id` uses the element/concat work around for its default value
Additional comments in line.
- both updated files passed checks
I have internal test kitchen / rspec test scenarios that exercise and tear down complete clusters,  with sample output provided in lieu of ability to open source the tests at this time.
```
#Custom matcher as awspec does not have eks resources at this time
eks cluster exists
should …
```
=> Fixed issue with 'workers_group_defaults_defaults.iam_role_id' and added explicit depends_on for 'update_config_map_aws_auth'

CHANGELOG.md, workers.tf
This allows the EKS cluster service to connect to the nodes on port 443. This is require to run the metrics-server, details [here](https://github.com/kubernetes-incubator/metrics-server/issues/45). Metrics-server is required to run horrizontal pod autoscalers.
AWS CFN is here: https://github.com/awslabs/amazon-eks-ami/blob/master/amazon-eks-nodegroup.yaml#L251-L260
=> Allowing 443 to nodes from EKS service

CHANGELOG.md, local.tf, workers.tf
Support launching worker node with non default tenancy.
Some companies have compliance requirements,  ec2 instances must be dedicated instances.
Without specific `placement_tenacy`, the value will keep emtpy(same as specified as `default`), won't show any surprising diff output for users not using before
=> Add option to change worker placement_tenancy.

CHANGELOG.md, local.tf, workers.tf
=> Add suspended_processes attributes to autoscaling_group

CHANGELOG.md, README.md, main.tf, variables.tf
Updated all occasions in documentation where `configure_kubectl_session` was still referenced. This field was 
* introduced in #13 (commit 8483fa2)
* and removed in #54 (commit 1a1d92da6636cdca1c2fe).
I hope it's ok that I didn't create an issue beforehand, ss this PR only changes documentation, not code.
=> Update documentation for removed `configure_kubectl_session`

CHANGELOG.md, cluster.tf, workers.tf
use the force detach for the IAM policies created for the cluster and workers. Had issues destroying the cluster
https://www.terraform.io/docs/providers/aws/r/iam_role.html#force_detach_policies
=> Destroying cluster causes some issues with removing policies

CHANGELOG.md, README.md, main.tf, variables.tf
Just a small change to add the new `--with-aggregate-type-defaults` option to terraform-docs instructions.
=> Adding new "--with-aggregate-type-default" option to terraform-docs

docs/autoscaling.md
awsRegion missing in example.
It's not working without it.
And added cloudProvider setting.
It's by default "aws" and not necessary at the moment. But it's to important and should be defined if default will change in the future.
=> AWS region was missing in example

CHANGELOG.md, README.md, aws_auth.tf, examples/eks_test_fixture/main.tf, examples/eks_test_fixture/variables.tf, variables.tf
We have a wrapper module around this (to enforce certain settings when invoked) and as such,  we're having issues passing in `map_accounts`, `map_roles`, `map_users` because of the `can not compute value of 'count'`. It pains me to have to do this, but this PR adds in count variables to be explicitly passed in for `map_accounts`,  `map_roles` and `map_users`  as a workaround for Terraforms limitations with respect to computed values for `count`  
[new-cluster-tf-plan.txt](https://github.com/terraform-aws-modules/terraform-aws-eks/files/2655806/new-cluster-tf-plan.txt)
[apply-output.txt](https://github.com/terraform-aws-modules/terraform-aws-eks/files/2655807/apply-output.txt)
=> Supply count for map_accounts, map_roles and map_users

CHANGELOG.md, README.md, cluster.tf, variables.tf, workers.tf
Since we cannot pass computed values to cluster_security_group_id or worker_security_group_id, I specified a cluster_create_security_group and worker_create_security_group.
=> Add ability to pass computed values to cluster_security_group_id and worker_security_group_id

README.md, main.tf
Use `sed` instead of `tail` for the `terraform-docs` command since it is more universally compatible. Thanks to @dpiddockcmp for your suggestion at https://github.com/terraform-aws-modules/terraform-aws-eks/pull/209#issuecomment-446671578
=> Use sed instead of tail for terraform-docs command

CHANGELOG.md, README.md, aws_auth.tf, data.tf, examples/eks_test_fixture/main.tf, local.tf, outputs.tf, variables.tf, workers.tf, workers_launch_template.tf
…licy.
Converting from using aws_launc_configuration to aws_launch_template to support mixed_instances_policy in the worker node's autoscaling group.
Addresses https://github.com/terraform-aws-modules/terraform-aws-eks/issues/194
=> Adding support for Launch Templates

CHANGELOG.md, aws_auth.tf
This is a fix for #238 
Fixes two problems:
* kubectl apply <aws auth config map> is actually tried up to 5 times
* terraform apply fails if said command fails after 5 attempts
Not sure how to add automated testing to this.
I did test my code changes manually against module version 1.8.0, and noticed it took `kubectl` 4 times before succeeding. 
I therefore thought it would be safer to increase the number of retries to 10
=> Fix zsh-specific syntax in retry loop within null_resource.update_config_map_aws_auth

CHANGELOG.md, aws_auth.tf
If you are trying to recover a cluster that was deleted, the current
code will not re-apply the ConfigMap because it is already rendered so
kubectl command won't get triggered.
This change adds the cluster endpoint (which should be different when
spinning up a new cluster even with the same name) so we will force a
re-render and cause the kubectl command to run.
This should be a simple way to work around the issue that we saw in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/234.
=> Fix issue where ConfigMap isn't applied to new cluster

CHANGELOG.md, local.tf, workers.tf, workers_launch_template.tf
This PR firstly enabled create_before_destroy for the ASG resource, previously it was killing the old ASG before creating the new one, felt like it made sense to just configure this for the ASG as it is already enabled for the launch configuration.
The second change was to enable the configuration of force_delete for the ASG, which is something I have found useful to do to enable myself to terminate an ASG that contains instance protected nodes.
I bundled them into one PR, if that is an issue I can split it out.
=> Enable create_before_destroy for ASG and enable force_delete to be configured

CHANGELOG.md, data.tf
Fixes what I think is a bug where `workers_group_defaults` were being used as default values for `launch_template_userdata`. Anyone that relies on that behaviour will need to specify defaults via `workers_group_launch_template_defaults` once this is merged.
=> Use launch template defaults for launch template userdata

CHANGELOG.md, local.tf, workers.tf, workers_launch_template.tf
Added `enabled_metrics` attribute to the worker groups configuration to optionally enable the collection of CloudWatch metrics.
Documentation: https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#enabled_metrics
=> Add enabled_metrics attributes to autoscaling_group

CHANGELOG.md, local.tf
Just adding the EBS optimized mapping for the g3s.xlarge instance type.
=> Adding the g3s.xlarge instance type ebs optimized mapping

CHANGELOG.md, README.md, examples/eks_test_fixture/main.tf, variables.tf, workers.tf, workers_launch_template.tf
Adding ability to configure worker group ASG tags which resolves #89
=> Worker group tags

CHANGELOG.md, README.md, aws_auth.tf, variables.tf
Added an option not to create aws_auth configmap.
I made it possible to apply kubectl apply without generating a file to correspond.
Refer issues
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/169
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/170
=> Added write_aws_auth_config option

CHANGELOG.md, README.md, cluster.tf, variables.tf, workers.tf
Add `permissions_boundary` as optional input, which will be attached to all IAM roles this modules creates.
On my project, we have an organizational requirement to apply a permissions boundary to all IAM roles.
=> Add optional permissions_boundary

outputs.tf
The terraform helm provider uses a kubectl config filename as a config parameter.
The eks module generates a kubectl config with a random filename.
In order to enable integration between the two and facilitate automated provisioning of an eks cluster, 
by passing the kubectl config filename as an input 
to the terraform helm provider, I added a new output to the eks module.
terraform helm provider: https://github.com/terraform-providers/terraform-provider-helm
=> Added output for generated kubeconfig filename

CHANGELOG.md, README.md, outputs.tf
This enables attaching additional policies, e.g. for using
encrypted volumes, to the cluster.
Signed-off-by: Steffen Pingel <steffen.pingel@tasktop.com>
=> Add outputs for cluster role ARN and name

README.md
Changed file name referred in description to match file from repo. Otherwise if you try to find it, you type locals.tf and no file is matched, while the correct file name is local.tf. Simple fix on a bit annoying typo.
=> annoying typo fix

CHANGELOG.md, README.md, data.tf, variables.tf
Currently the  worker AMI ID is always set to the latest for the Kubernetes version. This means when a new AMI is released then on next `terraform apply` the LC is updated. This is annoying for users who want to be able to pin the AMI to a release without having to lookup the AMI ID in each region.
With this PR we can just set this variable to a  [amazon-eks-ami](https://github.com/awslabs/amazon-eks-ami) release name:
```hcl
module "my_cluster" {
source                           = "git@github.com:terraform-aws-modules/terraform-aws-eks.git"
cluster_version                  = "1.11"
worker_ami_name_filter           = "v20190109"
...
```
=> Adding optional name filter variable to be able to pin worker AMI to a release

CHANGELOG.md, README.md, cluster.tf, variables.tf, workers.tf, workers_launch_template.tf
In some corporate environments you may only be allowed to create iam roles and policies within a certain path. Added an optional iam_path variable to allow support this type of configuration.
=> Add optional iam_path

CHANGELOG.md, local.tf, workers_launch_template.tf
Adding EBS encryption option for EKS workers in workers_launch_template
=> Adding workers_launch_template ebs encryption

CHANGELOG.md, workers.tf
Adds ec2:DescribeLaunchTemplateVersions to worker node IAM role to address scaling up from 0 for launch templates as noted here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md
- [ /] `terraform fmt` and `terraform validate` both work from the root and `examples/eks_test_fixture` directories (look in CI for an example)
=> add ec2:DescribeLaunchTemplateVersions action to worker node iam role

data.tf, local.tf, templates/userdata.sh.tpl
This enables support for `--enable-docker-bridge` in the latest eks ami.
=> Add support for --enable-docker-bridge

CHANGELOG.md, workers.tf, workers_launch_template.tf
Adds tags to all node groups to address https://github.com/terraform-aws-modules/terraform-aws-eks/issues/297:
- "k8s.io/cluster-autoscaler/{cluster-name}" (recommended by documentation in case of multiple clusters)
- "k8s.io/cluster-autoscaler/node-template/resources/ephemeral-storage" to support scaling from 0. Note that the PR to support this in CA is merged into master, but I haven't seen it merged into a release yet
I wasn't sure if it was ok to put these tags in all node groups. Doing so seemed ok since "cluster-autoscaler/disabled" is put in non-CA groups. Could potentially only put these in groups with "autoscaling_enabled," although might need help figuring out how
=> Add cluster name and ephemeral storage tags for cluster autoscaler

variables.tf, workers.tf
Example usage : we want our nodes to be able to update route53 record
for using external-dns.
```hcl
data "template_file" "eks_worker_additional_route53_policy" {
template = "${file("iam/route53_policy.json.tpl")}"
}
resource "aws_iam_policy" "eks_worker_additional_route53_policy" {
description = "Allow nodes to update our zone"
name = "${module.k8s_cluster01_label.id}-additional-route53-policy"
policy = "${data.template_file.eks_worker_additional_route53_policy.rendered}"
}
```
which defines the policy; then in the EKS module :
```hcl
module "cluster01" {
cluster_name = "cluster01"
<snip>
workers_addtional_policies = [
"${aws_iam_policy.eks_worker_additional_route53_policy.arn}"
]
workers_addtional_policies_count = 1
<snip>
```
=> Allow additional policies to be attached to worker nodes

CHANGELOG.md, local.tf, workers.tf
This enables placement groups to be specified for the worker groups.
=> Add support for placement groups

CHANGELOG.md, workers.tf
The docs at https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html specify that port 10250 is needed at a minimum for communication between the control plane, and the worker nodes; this is the port that the `kubelet` exposes. If you specify `worker_sg_ingress_from_port` as something like `30000`, then this minimum communication is not covered by the resource `aws_security_group_rule.workers_ingress_cluster `
I ran into this because I set `worker_sg_ingress_from_port = 30000`, and then deployed Helm onto my new cluster. I found that the communication was broken, and running a simple command like `helm list` resulted in the following error:
```
Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp 10.62.164.50:10250: i/o timeout
```
Adding port …
=> Adding minimum communication security group rule for Kubelet

CHANGELOG.md, cluster.tf, variables.tf
Added support for the eks private and public endpoints.
=> Add support for eks endpoint_private_access and endpoint_public_access

CHANGELOG.md, README.md, data.tf, local.tf, templates/userdata.sh.tpl
Replacing enable_docker_bridge with a generic option called bootstrap_extra_args
Fixes https://github.com/terraform-aws-modules/terraform-aws-eks/issues/310 https://github.com/terraform-aws-modules/terraform-aws-eks/issues/317
=> Replacing enable_docker_bridge with a generic option called bootstrap_extra_args

CHANGELOG.md, README.md, variables.tf
Eks kubernetes 1.12 got released this night: https://docs.aws.amazon.com/eks/latest/userguide/platform-versions.html
=> Update to 1.12

CHANGELOG.md, README.md, outputs.tf
Adds two outputs for IAM instance profile (role was already present, but not instance profile). See #323 
- [N/A] Tests for the changes have been added and passing (for bug fixes/features)
- [N/A] Test results are pasted in this PR (in lieu of CI)
- [N/A] Any breaking changes are highlighted above
=> adding IAM instance profiles to outputs, addresses #323

CHANGELOG.md, README.md, cluster.tf, outputs.tf, variables.tf
Adding EKS Control Plane logging options to this module.
This PR https://github.com/terraform-providers/terraform-provider-aws/pull/8216 was merged, allowing for the `enabled_cluster_log_types` option in the `aws_eks_cluster` resource.
**UPDATE: The terraform-aws-provider has relased [v2.6.0](https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v2.6.0), so the option `enabled_cluster_log_types` is now available.**
=> Adding EKS Control Plane logging options

CHANGELOG.md, README.md, docs/enable-docker-bridge-network.md
Add instructions on how to enable the docker bridge network
- [ NA ] `terraform fmt` and `terraform validate` both work from the root and `examples/eks_test_fixture` directories (look in CI for an example)
- [ NA ] Tests for the changes have been added and passing (for bug fixes/features)
- [ NA ] Test results are pasted in this PR (in lieu of CI)
Fixes #351
=> Add instructions on how to enable the docker bridge network

.pre-commit-config.yaml, CHANGELOG.md
Just switch to `https://` instead of `git://` for the urls in the pre-commit repos. Some corporate networks (like mine 😢 ) block external traffic on the `git` protocol.
- [ NA ] `terraform fmt` and `terraform validate` both work from the root and `examples/eks_test_fixture` directories (look in CI for an example)
- [ NA ] Tests for the changes have been added and passing (for bug fixes/features)
- [ NA ] Test results are pasted in this PR (in lieu of CI)
=> Switch to https for the pre-commit repos

CHANGELOG.md, README.md, local.tf, outputs.tf, workers_launch_template.tf
Minor fixes related to Launch Templates.
1. Set `root_encrypted` to `""`
Otherwise I get this error with the default EKS AMI:
```
Launching a new EC2 instance. Status Reason: Could not launch On-Demand Instances. InvalidBlockDeviceMapping - the encrypted flag cannot be specified since device /dev/xvda has a snapshot specified. Launching EC2 instance failed.
```
2. Split `aws_launch_template.workers_launch_template.security_groups` across multiple lines
For readability.
3. Add tags to `aws_launch_template.workers_launch_template`
4. Remove `=` from `iam_instance_profile` parameter. 
It's not supposed to be there: https://www.terraform.io/docs/providers/aws/r/launch_template.html#example-usage
5. Added outputs for 3 launch template attributes
- workers_launch_template_ids
- …
=> Fixes for Launch Templates

CHANGELOG.md, README.md, docs/spot-instances.md
Adding some detailed documentation about using this module to run EKS workloads on spot instances. Spot instances can save a lot of money but there's quite a few details that are required.
=> Adding doc about spot instances

CHANGELOG.md, README.md, local.tf
Disabling ASG process `AZRebalance` by default.
I can't think of a single reason why this wouldn't be a good idea to have disabled by default? If the ASG makes any changes to your instances, they need to be drained first and not terminated at will by the ASG.
=> Disabling ASG process AZRebalance by default

CHANGELOG.md, outputs.tf
Add cluster arn to outputs
- [x ] `terraform fmt` and `terraform validate` both work from the root and `examples/eks_test_fixture` directories (look in CI for an example)
- [x ] Tests for the changes have been added and passing (for bug fixes/features)
- [x ] Test results are pasted in this PR (in lieu of CI)
- [x ] I've added my change to CHANGELOG.md
- [x ] Any breaking changes are highlighted above
=> adding cluster arn to outputs

CHANGELOG.md, README.md, aws_auth.tf, cluster.tf, data.tf, local.tf, outputs.tf, variables.tf, workers.tf, workers_launch_template.tf
Fixes https://github.com/terraform-aws-modules/terraform-aws-eks/issues/282
=> Support custom IAM roles for cluster and workers

CHANGELOG.md, README.md, data.tf, examples/eks_test_fixture/main.tf, local.tf, variables.tf, workers.tf, workers_launch_template.tf
In this PR I'm having a large cleanup of all code related to Launch Templates (LTs)! This is part of an effort to make everything related to LTs first class. Apart from simply being the direction AWS is going, LTs have some other distinct advantages:
- Allows the use of overrides in the ASG for multiple instance types (e.g. c4 and m4 instances mixed)
- Allows the use of `mixed_instances_policy` ASG for multiple instance lifecycle options (e.g. spot and on-demand instances mixed)
- More network configuration options
- More placement options
- More [options for everything](https://www.terraform.io/docs/providers/aws/r/launch_template.html)
I am removing `local.workers_group_launch_template_defaults_defaults` as it's 96% the same as `local.workers_group_defaults_defaults`. The reason for the …
=> Cleaning up and deduplicating launch template related code

CHANGELOG.md, README.md, aws_auth.tf, cluster.tf, data.tf, docs/spot-instances.md, kubectl.tf, local.tf, outputs.tf, variables.tf, workers.tf, workers_launch_template.tf, workers_launch_template_mixed.tf
This PR adds a third worker group type, *Launch Template Mixed*, that includes 4x instance type overrides and a `mixed_instances_policy` in the ASG.
Also some cosmetic formatting changes for count and lifecycle options.
> Why the added complexity?
Advanced users will be able to use this to do things like running mixed instance and lifecycle types in the same ASG. This has very large cost benefit for users who want to use either spot or reserved instances without giving up scalability.
> Why choose 4 instance type overrides?
In TF it's currently not possible to let the user choose the amount as each item is a separate configuration block in the ASG resource. I think 4 is a good choice as there's a natural clustering for instances of similar types, e.g. `c/m/r/t + .large` or `c/m/r/t + …
=> Adding new mixed type of worker group with instance overrides and mixed instances policy

docs/spot-instances.md
Fix typos in spot instances document in example of section `Using Launch Templates`
`worker_group_launch_template_mixed` should be `worker_groups_launch_template_mixed` (group -> groups)
=> Fix typos in spot instances document

CHANGELOG.md, workers_launch_template_mixed.tf
Seems like the variable `manage_worker_iam_resources` to toggle the worker instance profile creation was not added to the mixed worker launch template. Without this change, I can't use that launch template in environments where AWS IAM changes are restricted.
=> Fix IAM instance profile toggle for mixed launch templates

CHANGELOG.md, README.md, cluster.tf, variables.tf
Added an option to encrypt the cloudwatch logs group using kms.
=> Added Option to use KMS key for cloudwatch logs group.

CHANGELOG.md, README.md, outputs.tf
Adds the name of the created Cloudwatch log group to the outputs of the module
=> add cloudwatch log group access

docs/spot-instances.md
Updated `suspended_processes` in docs to be a `list` otherwise terraform throws an error.
=> Fix suspended_processes to be a type list

CHANGELOG.md, docs/autoscaling.md, examples/spot_instances/main.tf, local.tf
According to the CA's [document](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#using-autoscalinggroup-mixedinstancespolicy),  that the instance types should have the same amount of RAM and number of CPU cores, since this is fundamental to CA's scaling calculations. Using mismatched instances types can produce unintended results.
I and #422 was bitten by this
=> Update default override instance types to work with Cluster Autoscaler

CHANGELOG.md, local.tf, workers_launch_template.tf, workers_launch_template_mixed.tf
This PR makes configurable 'T2/T3 unlimited' param for workers.
Used 'standard' mode as default to avoid unexpected paying higher costs.
This parameter can be configured for Launch Templates only, don't work for Launch Configuration even via AWS API.
=> Configure 'cpu_credits' for workers (#253)

CHANGELOG.md, local.tf, workers_launch_template.tf
Correct me if I'm wrong: Currently, the only way to request spot instances in a launch template is by specifying pools. The change here may be not ideal, but it seems to have worked for me. 
Going by this:
https://www.terraform.io/docs/providers/aws/r/launch_template.html#market-options
It should be possible to implement this, maybe not ideally with this PR but with a similar approach. This is more a feature request than a full PR.
Reference: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotMarketOptions.html
=> added market options to request spot instances without pools

README.md
Currently the example usage is an object, where in `local.tf` the default is defined as a list (https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/local.tf#L35), and `workers.tf` is using a list of objects (https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L68).
=> chore: fix README.md worker_groups tags syntax

CHANGELOG.md, README.md, examples/basic/main.tf, examples/launch_templates/main.tf, examples/spot_instances/main.tf
AWS docs state:
> Your VPC must have DNS hostname and DNS resolution support. Otherwise, your worker nodes cannot register with your cluster. For more information, see Using DNS with Your VPC in the Amazon VPC User Guide. 
- https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html
From that it seems like it should always be enabled, no matter what kind of VPC is used. I added it to the basic example which I used and had error messages with DNS resolution appearing in the logs on the nodes. Interestingly enough, without DNS resolution the cluster appears to sometimes work and sometimes not. It's hard to run experiments though, so as per the docs, it should be enabled.
Question: do we want to play it safe and enable DNS resolution in all examples (even public VPC)?
- [v] …
=> VPC: `enable_dns_hostnames = true` in examples

CHANGELOG.md, workers_launch_template.tf, workers_launch_template_mixed.tf
EKS Nodes created by "workers_launch_template*.tf" do not have EBS Volumes tags.
=> Support for tagging EBS Volumes created by "workers_launch_template*.tf"

CHANGELOG.md, workers.tf
Added new tag to worker.tf with `autoscaling_enabled = true` flag due to recent changes in [helm chart]((https://github.com/helm/charts/commit/9587fab922920a33247f3f2b815ce0585a995562#diff-0b4714d45280a44e975e49e088149d8a)).
=> Additional tag for autoscaling enabled

aws_auth.tf, data.tf
Fixed formatting, so it passes with v0.12.6.
=> Fix fmt for v0.12.6

CHANGELOG.md, versions.tf
Inform terraform of the providers' minimum version requirements. An error will be thrown at `init` if the including plan does not request high enough versions.
This would have helped a little with my recent upgrade. And if kept up to date will reduce the number of issues caused by the user's provider being out of date. Something seen occassionally with the 0.11 version of the module.
I successfully did an apply and destroy of the basic example with the following versions:
```
$ terraform -version
Terraform v0.12.6
+ provider.aws v2.8.0
+ provider.local v1.2.2
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.template v2.1.2
```
=> Add `required_providers` to set minimum versions

CHANGELOG.md, aws_auth.tf, cluster.tf, data.tf, workers.tf
Add tags for the log group, the workers IAM role and the workers root volume when using a launch template.
=> Adding tags for Log groups and workers IAM role

CHANGELOG.md, local.tf
Fixes #402.
Replace the calls to coalesce() in local.tf with the ternary operator to avoid the errors when both arguments to coalesce() are empty (this is a breaking change in Terraform v0.12). The usage of the coalesce()s seemed to be to emulate the then-missing ternary operator, so it the intent in the code should also now be clearer.
=> Fix errors from usage of coalesce (#402)

CHANGELOG.md, docs/spot-instances.md, local.tf, workers_launch_template.tf
Allow the creation of spot nodegroups using Launch Templates without resorting to Mixed Policy (due to certain incompatibilities with cluster autoscaler, for example). 
Edit: Switched to using `dynamic` block, instead of a separate `workers_launch_template_spot`.
=> Allow launch template spot instances without mixed policy

CHANGELOG.md, examples/basic/main.tf
Added the "kubernetes.io/role/elb" tag to the public subnets in the
basic example.
Per documentation, ELB tag values are supposed to be "1". ELB tag values
being "true" are known not to work with aws-alb-ingress-controller.
https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html
https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html
=> Basic example: correct ELB tags

CHANGELOG.md, README.md, variables.tf
You cannot filter the public cluster endpoint.
Update documentation to remove historical mention of adding caller's IPv4 to the cluster security group. This behaviour was originally removed in v1.5.0
Fixes #471
=> Update cluster_security_group_id doc

CHANGELOG.md, templates/userdata.sh.tpl
Wrapping kubelet_extra_args in double quotes instead of single quotes
Fixes #473
=> Wrapping kubelet_extra_args in double quotes

CHANGELOG.md, local.tf, versions.tf, workers.tf, workers_launch_template.tf, workers_launch_template_mixed.tf
This PR will allow user to recreate autoscalling groups when launch template or launch configuration changes.
Related to https://github.com/terraform-aws-modules/terraform-aws-eks/issues/462
=> add option to recreate ASG when LT or LC changes

CHANGELOG.md, local.tf, workers.tf, workers_launch_template.tf, workers_launch_template_mixed.tf
This PR will allow user to create initial life cycle hooks for autoscaling groups.
Related to #462
=> add initial lifecycle hooks for autosacling groups

workers.tf
Launch configuration doesn't have version.
Resolves #479
=> Fix this object does not have an attribute named "latest_version"

CHANGELOG.md, workers_launch_template.tf
This fixes the `market_type` passing when generating the `workers_launch_template`. The previous version would not populate the `instance_market_options.market_type` even if the corresponding value was passed.
=> Fix launch template market option expansion

outputs.tf
More info https://github.com/terraform-aws-modules/terraform-aws-eks/pull/514#issuecomment-532654473
=> Output empty string when cluster identity is empty

CHANGELOG.md, README.md, data.tf, variables.tf
Current implementation doesn't allow to use Amazon EKS-Optimized AMI with GPU Support(https://docs.aws.amazon.com/eks/latest/userguide/gpu-ami.html), because of hardcoded AMI filter prefix "amazon-eks-node".
This patch allow to define different AMI filter prefix, i.e. "amazon-eks-gpu-node", but default is still set to "amazon-eks-node"
=> Gpu workers support

CHANGELOG.md, local.tf
Setting `null` as default for `target_group_arns` attribute of worker autoscaling group prevents Terraform from overwriting `aws_autoscaling_attachment`s created in other modules targeting worker ASG. In my opinion, this is more desirable default compared to `[]`, which overwrites autoscaling group attachments created in other modules.
Related issue: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/499
=> Use null as default value for target group ARNs

CHANGELOG.md, README.md, variables.tf, workers.tf, workers_launch_template.tf
Related to https://github.com/terraform-aws-modules/terraform-aws-eks/issues/527
=> Add option to enable lifecycle hooks creation

docs/spot-instances.md
Removing the `worker_groups_launch_template_mixed` variable from examples.
=> remove the launch template mixed variable from examples

CHANGELOG.md, README.md, outputs.tf, variables.tf, workers.tf
The IAM policies for the node autoscaler and AWS CNI have write permissions and are assigned to the nodes by default. These could potentially be dangerous to the stability of the cluster if accessed by a rogue pod as they are the default role received.
I'm currently looking at the new OIDC IAM integration. The [AWS documentation](https://docs.aws.amazon.com/eks/latest/userguide/restrict-ec2-credential-access.html) has an example for using iptables to block access to the metadata service but this broke some pods like the alb-ingress-controller. Not a great situation. I could put pods that need access to the metadata service on the host network but I don't fancy that solution. The only other option is to make the default node role as harmless as possible.
Also made creation of the …
=> Make "dangerous" policy attachments optional

CHANGELOG.md, cluster.tf, versions.tf
terraform-provider-aws v2.31.0 has been released
resource/aws_eks_cluster: Add tags argument (#10307)
https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v2.31.0
https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-eks-supports-cluster-tagging/
=> Add tags to eks cluster introduced by terraform-provider-aws 2.31.0

CHANGELOG.md, local.tf, workers.tf, workers_launch_template.tf
This change was suggested in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/386.
It replaces the mapping of ebs_optimized instance types with a list of instance types that do not support ebs_optimized.
I generated the list of instance types that do not support the ebs_optimized flag by getting all of the instances that support it from here https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html and comparing it with a list of all instance types generated using
```
curl https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json | jq -r '.products[].attributes["instanceType"]' | sort -u | grep '\.'
```
This doesn't remove any of the current instance types where ebs_optimized is `false`, and it adds the following instance types:
``` …
```
=> change ebs_optimized mapping to list where not supported

CHANGELOG.md, README.md, data.tf, variables.tf
In some environments one may be required to customise the AMI used by the worker nodes.
This PR allows for specifying a custom AMI to use for the worker nodes in a backwards-compatible way (and I think it closes #540).
=> Allow for specifying a custom AMI for the worker nodes.

CHANGELOG.md, README.md, kubectl.tf, variables.tf
Currently the `kubectl` configuration file is always written to a file named `kubeconfig_${var.cluster_name}`. I want to write to `~/.kube/config` instead, so allow `var.config_output_path` to refer to a file as well as a directory.
=> Allow `config_output_path` to specify the full path

data.tf
The template file data source was injecting a region variable that is not defined in the template. Once removed the variable the aws region data source was not used anywhere else, so it is removed as well.
=> Remove region from vars mapping for kubeconfig

CHANGELOG.md, examples/launch_templates/main.tf, examples/spot_instances/main.tf, versions.tf
https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#0122-june-12-2019
Bump minimum terraform version in order to avoid the following errors :
```
Error: Call to unknown function
on .terraform/modules/my-cluster/terraform-aws-modules-terraform-aws-eks-1be1a02/aws_auth.tf line 82, in data "template_file" "config_map_aws_auth":
82:     map_users    = yamlencode(var.map_users),
There is no function named "yamlencode".
Error: Call to unknown function
on .terraform/modules/my-cluster/terraform-aws-modules-terraform-aws-eks-1be1a02/aws_auth.tf line 83, in data "template_file" "config_map_aws_auth":
83:     map_roles    = yamlencode(var.map_roles),
There is no function named "yamlencode".
Error: Call to unknown function
on .terraform/modules/my-cluster/terraform-aws-modules-terraform-a …
```
=> Increase minimum terraform version to include yamlencode

CHANGELOG.md, README.md, aws_auth.tf, data.tf, docs/faq.md, local.tf, templates/userdata_windows.tpl, templates/worker-role.tpl, variables.tf, workers.tf, workers_launch_template.tf
[EKS Windows container support is generally available](https://aws.amazon.com/ko/blogs/aws/amazon-eks-windows-container-support-now-generally-available/) now. This PR adds support for Windows worker nodes, by adding `platform` variable as an worker config.
I also added `worker_ami_name_filter_windows` and `worker_ami_name_filter_windows_prefix` variables, because naming pattern of EKS optimized AMI for Windows are totally different from linux AMIs.
User-data scripts are came from the equivalent CloudFormation snippet: https://amazon-eks.s3-us-west-2.amazonaws.com/cloudformation/2019-10-08/amazon-eks-windows-nodegroup.yaml
=> Add Windows support

CHANGELOG.md, data.tf, local.tf
This addresses issue #564 
Adds a `custom_userdata` property to `worker_groups` that can be used to override the full userdata template file.
=> Allow the userdata template to be replaced

.github/workflows/lint.yml, CHANGELOG.md
Add a Github Action check to try to validation the minimum versions listed. This won't catch everything but it does catch the two recent cases:
- `yamlencode()` use from terraform 0.12.2 #570 
- tags on `aws_eks_cluster` in aws 2.31.0 #550
=> Add Action check against minimum versions

CHANGELOG.md, outputs.tf
The worker_iam_instance_profile_names, and worker_iam_instance_profile_arns would not give expected results is the EKS Cluster is created with worker_groups_launch_template or mixed options. Added concat list to output so they give results in case cluster is created with mixed or worker_group_launch_template properties.
=> Update worker_iam_instance_profile outputs for launch template use

CHANGELOG.md, kubectl.tf
Fix warning with interpolation-only expresions with terraform 0.12.14,
fixes #593
=> Fix deprecated interpolation-only expression

CHANGELOG.md, data.tf
Fix issue #582. I followed suggestion [here](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/582#issuecomment-550387472) with some modification.
Also, I checked every AWS region to check existence of that image.
```
aws ec2 describe-images --owners 801119661308 --filters "Name=platform,Values=windows" "Name=name,Values=Windows_Server-2019-English-Core-EKS_Optimized-1.14-*" --region=$region | jq '.Images | .[] | [.Name, .ImageId, .CreationDate]'
```
Results: `Windows_Server-2019-English-Core-EKS_Optimized-1.14-*` AMI exists on all regions except ca-central-1 and us-west-1. But EKS is not available on ca-central-1 & us-west-1, so this is OK.
=> Fix broken terraform plan/apply on a cluster < 1.14 (Fix #582)

CHANGELOG.md, aws_auth.tf
As mentioned in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/591
The current script utilized to update the `aws-auth` ConfigMap runs the creation of the `kube_config.yaml` and `aws_auth_configmap.yaml` in parallel to the `kubectl apply` command being run. 
As mentioned in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/341
Upon failure, the current script does not provide an exit code. 
This PR seeks to solve both of these issues.
=> Run aws-auth Update Commands in Sequence and not Parallel

aws_auth.tf
Simply having ${yamlencode(var.map_roles)} in mapRoles for aws-auth creates a empty [] at the end after adding the default roles.
Changing it to be added only when its not empty
=> remove empty [] to mapRoles object in aws-auth

CHANGELOG.md, aws_auth.tf
Please see the following comment for reson this reverting
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/606#issuecomment-561795104
=> Fix PR merge: #606

aws_auth.tf
Previous PRs (https://github.com/terraform-aws-modules/terraform-aws-eks/pull/606#issuecomment-562658290) to the same issue wiped out entire mapRoles from `aws-auth`
This is an alternative solution using `length()` function. See https://github.com/terraform-aws-modules/terraform-aws-eks/pull/614
Please, review PR https://github.com/terraform-aws-modules/terraform-aws-eks/pull/614 before merging this PR
=> remove empty [] to mapRoles in aws-auth (revised)

.github/workflows/lint.yml, CHANGELOG.md, versions.tf
Additions in #602 trigger a bug in older terraforms. It was fixed in 0.12.9.
```
Error: Invalid for_each set argument
on ../../node_groups.tf line 30, in resource "aws_iam_role_policy_attachment" "node_groups_additional_policies":
30:   for_each = toset(var.workers_additional_policies)
The given "for_each" argument value is unsuitable: "for_each" supports maps
and sets of strings, but you have provided a set containing type dynamic.
```
=> Bump minimum Terraform to 0.12.9

CHANGELOG.md
I was trying to find the upgrade docs for the kubernetes provider. It 404'd as the content had been moved to the changelog itself. Plus some other minor tweaks and attributions.
=> Minor tweaks to changelog

CHANGELOG.md, README.md, irsa.tf, variables.tf
Added support to create IAM OpenID Connect Identity Provider to enable EKS Identity Roles for Service Accounts (IRSA).
This should address the issue in TF: https://github.com/terraform-providers/terraform-provider-aws/issues/10104
=> Add IRSA support

CHANGELOG.md, README.md, cluster.tf, local.tf, variables.tf, workers.tf
1. Main change on cluster.tf `aws_security_group_rule.cluster_https_worker_ingress` intended to whitelist port 443 for newly created security group or self attach security group from worker's security group. Self attach control plane security group will not able to whitelist worker security group before it get created therefore additional step will required.
2. Revert PR #186 as Terraform v0.12.x fixed "count cannot be computed" issue
2.1  Remove `cluster_create_security_group` and `worker_create_security_group` to improve consistency. There is no guarantee/enforcement when you set `cluster_create_security_group` or `worker_create_security_group` to `false`, user will also provide `cluster_security_group_id` or `worker_security_group_id`.
=> Control plane security group always whitelist worker security group and revert #186

CHANGELOG.md, README.md, outputs.tf
This PR adds the IAM role ARNs of node groups in the outputs in the form of a map
=> Adding node group iam role arns to outputs

CHANGELOG.md, README.md, outputs.tf
Please explain the [changes](url) you made here and link to any relevant issues.
This PR adds the OICD Provider ARN to outputs when `enable_irsa = true`. This needed when creating IAM policy documents/roles for Service Accounts, an example of which can be seen [here](https://www.terraform.io/docs/providers/aws/r/eks_cluster.html#enabling-iam-roles-for-service-accounts).
Note: The output is conditionally generated only when `enable_irsa = true`. When `enable_irsa = false` no output will be given, which [is preferable](https://github.com/hashicorp/terraform/issues/23222#issuecomment-547421898) to it returning a bad value, such as the empty string, which could then lead to misconfigured downstream resources.
=> Add the OIDC provider ARN to outputs

CHANGELOG.md, aws_auth.tf, cluster.tf, versions.tf
I experience intermittent problems applying config_map as cluster is not immediately ready to respond to kubectl after create. This PR adds a null resource that sleeps until the cluster responds to kubectl.
=> Wait cluster responsive

.pre-commit-config.yaml, README.md, modules/node_groups/README.md
1. Re-geneate docs with the latest version of terraform-docs [0.7.0](https://github.com/segmentio/terraform-docs/releases/tag/v0.7.0) to escape underscores (`variable\_with\_underscore`).
Should resolves docs generation issues for https://github.com/terraform-aws-modules/terraform-aws-eks/pull/667 and https://github.com/terraform-aws-modules/terraform-aws-eks/pull/666
1. Update pre-commit-terraform version
=> Re-generate docs with terraform-docs 0.7.0 and bump pre-commit-terraform version

CHANGELOG.md, modules/node_groups/node_groups.tf
Resolves #681
Add an `ignore_lifecycle` rule to prevent Terraform from scaling down ASG behind AWS EKS Managed Node Group. This is important as the ASG will be scaled up by a deployed cluster autoscaler, and shortly thereafter the Managed Node Group will reflect the new desired size. This brings the functional behavior of `desired_capacity` (or `desired_size` in the actual `aws_eks_node_group` resource) in line with the current behaviour of ASGs `desired_capacity` on worker groups managed by this module: https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/workers.tf#L139-L142
=> Ignore changes to desired_size of node_groups

CHANGELOG.md, cluster.tf
Don't create ingress rule if worker security group exists
Disable creation of ingress rule on worker security group if exists
=> Don't create ingress rule if worker security group exists

CHANGELOG.md, docs/iam-permissions.md
The suggested policy in `iam-permissions.md` is missing to include the `iam:GetOpenIDConnectProvider` permission hence Terraform plan fails to complete with the error:
```
AccessDenied: User: arn:aws:sts::<redacted>:assumed-role/<iam_role>/ is not authorized to perform: iam:GetOpenIDConnectProvider on resource: arn:aws:iam::<redacted>:oidc-provider/oidc.eks.ap-southeast-2.amazonaws.com/
``` 
After including this permission Terraform completes running the plan
=> Add iam:GetOpenIDConnectProvider grant to docs/iam-permissions.md

CHANGELOG.md, modules/node_groups/README.md, modules/node_groups/node_groups.tf
I added an additional parameter `name` to managed node groups in order to be able to manually provide a name for the node group. Resolves #698.
=> Add option to set the name of a node group manually

CHANGELOG.md, README.md, variables.tf
This is addressing https://github.com/terraform-aws-modules/terraform-aws-eks/issues/741
Currently after creating eks cluster there is `local-exec` loop checking availability of API endpoint
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/10ca272e5b7ce006a721c99ef8906720ff5cd6ee/variables.tf#L201-L205
This behaviour is working totally fine, but it require installed `curl`, which is missing in official Hashicorp docker image ( `hashicorp/terraform` ). Instead there is `wget`:
```
$ docker run -ti --entrypoint='' hashicorp/terraform sh
/ # which curl 
/ # which wget
/usr/bin/wget
```
This can be workaround by using following input module variable:
```
wait_for_cluster_cmd = "until wget --no-check-certificate -O - -q $ENDPOINT/healthz >/dev/null; do sleep 4; done"
```
So …
=> change default value for wait_for_cluster_cmd

CHANGELOG.md, README.md, examples/basic/main.tf, examples/irsa/main.tf, examples/launch_templates/main.tf, examples/managed_node_groups/main.tf, examples/spot_instances/main.tf
Semantic version fails on latest kubernetes provider,  pinning the version on examples exactly to 1.10.0 resolves many issues 
=> Pin version for kubernetes provider across examples to exactly 1.10.0

CHANGELOG.md, README.md, variables.tf
In issue #726, we concluded that timeout should be the same as from upstream aws provider. 
Therefore, I've changed it to 30m.
=> changing timeout

CHANGELOG.md, docs/spot-instances.md
Update documentation to schedule cluster-autoscaler on normal instances.
The documentation states the cluster autoscaler should be scheduled on spot instances. This is incorrect. It's the exact opposite.
=> cluster-autoscaler shouldn't be scheduled on spot

CHANGELOG.md, local.tf, workers.tf
This adds the `encrypted` option found in the `root_block_device` stanza in the `aws_launch_configuration` resource. Reuses the field currently utilized by worker_launch_templates to perform the same function.
=> Adding encrypted option to root_block_device of launch_configuration

CHANGELOG.md, cluster.tf, data.tf, local.tf, workers.tf
=> use correct policy arns for CN regions (cn-north-1, cn-northwest-1)

CHANGELOG.md, local.tf, workers.tf, workers_launch_template.tf
Adds support for the max instance lifetime parameter in the ASG. This will allow old instances (those running longer than a specified number of seconds) to be automatically terminated.
Fixes #768.
=> Add support for ASG max instance lifetime

CHANGELOG.md, local.tf, workers.tf, workers_launch_template.tf
Add [default_cooldown](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#default_cooldown)
and [health_check_grace_period](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#health_check_grace_period)
options
=> Add ASG cooldown and health_check_grace_period

CHANGELOG.md, workers.tf
Fix max_instance_lifetime for workers added with https://github.com/terraform-aws-modules/terraform-aws-eks/pull/769
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/770#issuecomment-596937299
cc @sidprak
=> fix max_instance_lifetime for workers

.chglog/CHANGELOG.tpl.md
=> fix: fix git-chglog template to format changelog `Type` nicely

README.md, variables.tf
The current default command for `wait_for_cluster` will happily sit forever in a failing state. Module previously had a timeout before the switch to kubernetes provider in 8.0.0.
Defaults to 5 minutes of sleeps. May be a lot longer depending on how wget hangs. 
Have tested logic on bash 3 (for those older Mac users), zsh, bash 5, and busybox (default in alpine)
```
$ docker run --rm -it alpine /bin/sh -c 'for i in `seq 1 60`; do false && exit 0 || true; sleep 0; done; echo TIMEOUT && exit 1' ; echo $?
TIMEOUT
1
$ docker run --rm -it alpine /bin/sh -c 'for i in `seq 1 60`; do true && exit 0 || true; sleep 0; done; echo TIMEOUT && exit 1' ; echo $?
0
```
Sample failure output (I lowered the seq count because ain't got all day):
```
module.eks.null_resource.wait_for_cluster[0]: Creating... …
```
=> improvement: Add timeout to default wait_for_cluster_cmd

cluster.tf, examples/create_false/main.tf, examples/create_false/variables.tf
Simple example for the module with `create_eks = false` set. Mainly useful for testing changes that add new resources.
This also "fixes" the module so that the plan applies cleanly. It was waiting forever for a non-existent cluster to respond.
=> fix: Create false

aws_auth.tf, templates/worker-role.tpl
The current module generates the `roles` item of the `aws-auth` ConfigMap using string concatenation. Building a data structure from concat is often fraught with troubles. We can see that with the edge case of having no roles defined generating invalid YAML.
This change uses Terraform primitive data types and then a final yamlencode() to create the `roles`.
Fixes #689
This shouldn't be a breaking change although it will cause an update to the `aws-auth` ConfigMap to remove unnecessary blank lines.
```hcl
module "eks" {
source       = "../.."
cluster_name = local.cluster_name
subnets      = module.vpc.private_subnets
vpc_id       = module.vpc.vpc_id
}
```
Previous:
```yaml
apiVersion: v1
data:
mapAccounts: |
[]
mapRoles: |2+
mapUsers: |
[]
kind: ConfigMap
metadata:
name: aws-auth …
```
=> improvement: Generate `aws-auth` ConfigMap's roles from Object. No more string concat.

cluster.tf
Setting `cluster_create_security_group = false` and not setting `cluster_security_group_id` causes the cluster to be recreated on every apply.
I did try setting `cluster_security_group_id = null` but then terraform complains that there's a null item inside a list and that I'm a very bad person for doing something so rude.
Fixes #797
=> fix: Do not recreate cluster when no SG given

node_groups.tf
Setting `manage_aws_auth = false` removes the ordering dependency between node_group and eks_cluster generating an error on first apply. This change ensures that the eks_cluster is created before trying to create the node_group.
Fixes #793
=> fix: Add node_group direct dependency on eks_cluster

README.md, examples/basic/main.tf, examples/irsa/main.tf, examples/launch_templates/main.tf, examples/managed_node_groups/main.tf, examples/secrets_encryption/main.tf, examples/spot_instances/main.tf, versions.tf
Set the required kubernetes provider version to 1.11.1.
Looks like the original breaking changes in 1.11.0 have been fixed. And hopefully this also resolves the problems people were seeing with the provider randomly trying to modify their default or localhost clusters. Or at least we'll encourage further testing of the provider 😁 
Not sure how you want to classify this. It's not really a breaking change but it may cause terraform to fail to init if users have set `version = "1.10"` like we had in the examples.
Fixes #733
Fixes #713 [probably]
=> improvement: Require k8s provider >=1.11.1

cluster.tf
In #812 we have a situation where when one attempts to `terraform destroy` and `cluster_endpoint_public_access` is `false` then an error will be encountered:
`Error: Get https://SNIP.eks.amazonaws.com/api/v1/namespaces/kube-system/configmaps/aws-auth: dial tcp IP:443: i/o timeout` (`IP:443` is the IP of the endpoint).
This change has been tested with `cluster_endpoint_public_access` as `true` and as `false`. I tested it by running `tf apply && tf destroy` in each case, verifying that it completed.
Resolves #812
=> fix: Fix destruction failure when talking to EKS endpoint on private network

README.md, data.tf, local.tf
Use `aws_partition` data resource to dynamically build the IAM policy ARNs instead of branching by region name.
=> improvement: Use aws_partition to build IAM policy ARNs

workers_launch_template.tf
Our company has a policy on the mandatory tags of resources.
If "Tag instances" are not set in the Launch Template, an error occurs:
```
Error: Error creating AutoScaling Group: AccessDenied: You are not authorized to use launch template: lt-0d9b738051139aab9
status code: 403, request id: 8db8541f-69d2-4vdc-b4cb-25c920ed342f
on .terraform/modules/eks/terraform-aws-modules-terraform-aws-eks-ca3d1e1/workers_launch_template.tf line 3, in resource "aws_autoscaling_group" "workers_launch_template":
3: resource "aws_autoscaling_group" "workers_launch_template" {
```
The reason is the invocation of "ec2: RunInstances" when the Launch Template is attached to the AutoScaling Group at creation.
=> feat: Add instance tag specifications to Launch Template

README.md, aws_auth.tf, data.tf, modules/node_groups/README.md
fix: EC2 principal for EKS worker role assume policy
Add logic to correctly handle EC2 principal service endpoint in China region for EKS Worker role assume policy.
=> feat: Add support for EC2 principal in assume worker role policy for China

aws_auth.tf
Adds a line to make `worker_group_launch_templates` consistent with `worker_groups` and fix an error that could arise during `terraform destroy`
[#841 ](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/841)
=> fix: Fix terraform destroy errors when using worker_group_launch_templates

README.md, outputs.tf
Add cluster security group output as "primary cluster security group id".  
This is a short term fix to provide the cluster security group id until 1.16 is released and node groups can be refactored to move cluster security group id to additional security group id.   With 1.16 release, 1.13 will no longer be maintained which will cause the issues with backwards compatibility to go away because the old node groups will no longer be supported.  
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/799
and 
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/792
=> fix: Add `vpc_config.cluster_security_group` output as primary cluster security group id

examples/basic/main.tf, examples/irsa/main.tf, examples/launch_templates/main.tf, examples/managed_node_groups/main.tf, examples/secrets_encryption/main.tf, examples/spot_instances/main.tf
Remove useless external template provider after https://github.com/terraform-aws-modules/terraform-aws-eks/pull/854
=> docs: Remove useless template provider in examples

.travis.yml, CHANGELOG.md, local.tf, workers_launch_template.tf, workers_launch_template_mixed.tf
Add `cpu_credits` param for the workers defined in `worker_groups_launch_template*` for tf0.11 branch.
Same as https://github.com/terraform-aws-modules/terraform-aws-eks/issues/253 but for terraform v0.11.*
=> improvement: Add cpu_credits for tf0.11

README.md, kubectl.tf, versions.tf
Kubeconfig does not really need to be executable, so let's not create it with executable bit set.
=> feat: Create kubeconfig with non-executable permissions

node_groups.tf
After some tests, I've noticed that all inputs of the `null_data_source` are already know.
```shell
<= data "null_data_source" "node_groups"  {
+ has_computed_default = (known after apply)
+ id                   = (known after apply)
+ inputs               = {
+ "aws_auth"        = "kube-system/aws-auth"
+ "cluster_name"    = "test-eks-uIVr3XSp"
+ "role_CNI_Policy" = "test-eks-uIVr3XSp20200505210731845200000005-20200505210733402400000008"
+ "role_Container"  = "test-eks-uIVr3XSp20200505210731845200000005-20200505210733399800000007"
+ "role_NodePolicy" = "test-eks-uIVr3XSp20200505210731845200000005-20200505210733441800000009"
}
+ outputs              = (known after apply)
+ random               = (known after apply)
}
```
The unknown values are computed one like `random`, `id`, etc. and …
=> fix: Use splat syntax for cluster name to avoid `(known after apply)` in managed node groups

.chglog/CHANGELOG.tpl.md, .chglog/config.yml, README.md
Add notes and breaking change about Kubernetes 1.16 before https://github.com/terraform-aws-modules/terraform-aws-eks/pull/871 get merged.
By commiting this, we'll generate changelog like this:
------------------
DOCS:
- Add notes for Kubernetes 1.16
- Remove useless template provider in examples ([#863](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/863))
BUG FIXES:
- Use splat syntax for cluster name to avoid `(known after apply)` in managed node groups ([#868](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/868))
FEATURES:
- Create kubeconfig with non-executable permissions ([#864](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/864))
- Change EKS default version to 1.16 ([#857](https://github.com/terraform-aws-modules/terraform-aws …
=> docs: Add notes for Kubernetes 1.16

local.tf, workers_launch_template.tf
Updating Launch Templates with aws provider 2.61.0 generates an error when creating the ASG or attempting to launch new instances. This is caused by the aws provider adding support to the launch template for `placement.partition_number`. I think the root issue is go-aws-sdk defaulting this to 0 as it's an integer and the module setting the placement block when no placement group is in use. Having partition_number set but no placement group name is a validation error. For example when creating a new ASG:
`Error: Error creating AutoScaling Group: ValidationError: You must use a valid fully-formed launch template. You cannot use PartitionNumber with a Placement Group that does not exist. Specify a valid Placement Group and try again.`
Resolve the issue by not setting the placement block if …
=> fix: Fix Launch Templates error with aws 2.61.0

CHANGELOG.md
=> chore: update changelog for release 12.0.0

CHANGELOG.md, README.md, local.tf, workers.tf, workers_launch_template.tf, workers_launch_template_mixed.tf
- adds max_instance_lifetime parameter to the ASG resources.
This configuration is useful when implementing a "phoenix server" patter to rotate older instances.
=> improvement: add max_instance_lifetime to asg for tf0.11

outputs.tf
Make the `cluster_id` module output block on the `null_resource.wait_for_cluster`. Users do not need to re-implement the null resource if they also want to create kubernetes resources in the same configuration.
This won't do anything for users with `manage_aws_auth = false`
From the rejected #884.
=> improvement: cluster_id output blocks on wait_for_cluster

aws_auth.tf
`aws-iam-authenticator` has an open issue where it will not recognize
IAM roles that include paths. This change causes the path supplied to
`var.iam_path` to be stripped when generating the `aws-auth` ConfigMap
in order to work around this.
https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/153
Fixes #893
=> fix: Work around path bug in aws-iam-authenticator

README.md, local.tf, outputs.tf, variables.tf, workers.tf
Adds two security group rules allowing pods running on worker nodes to communicate with pods using the primary cluster security group (such as pods running on Fargate).
See https://github.com/terraform-aws-modules/terraform-aws-eks/pull/866#discussion_r428140829.
=> feat: Allow communication between pods on workers and pods using the primary cluster security group

templates/kubeconfig.tpl
In order to be a text file according to POSIX, file needs to be composed of
text lines. Text line is defined as sequence of characters ending in \n. Sadly,
`~}` did strip everything including the \n, so the kubeconfing did not end
with a new line. Output empty string at the end to make sure of it.
=> fix: Ensure kubeconfig ends with \n

.travis.yml, CHANGELOG.md, README.md, cluster.tf, local.tf, variables.tf
- Add `cluster_endpoint_public_access_cidrs` parameter for for restricting access to the public API endpoint for `tf0.11` branch
- Fix failed `max_instance_lifetime` default value, which was added in #879 for `tf0.11` branch
=> improvement: Add cluster_endpoint_public_access_cidrs for tf0.11

README.md, outputs.tf
References #888.
This PR exposes the `cluster_https_worker_ingress` security group rule as an output value.
In order to ensure proper ordering when running `terraform destroy`, I need to be able to establish an explicit dependency on the exposed resource because that resource allows pods to communicate with the control plane. Without being able to declare the dependency, terraform will likely destroy the rule early, which will prevent other resources from proper destruction.
=> feat: Add aws_security_group_rule.cluster_https_worker_ingress to output values

cluster.tf
Issue: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/914
This fix corrects an incorrect behavior, in which the module requires the user to have enable `manage_aws_auth` variable for the creation of a security_group with the ingress rules necessary to access the private endpoint of the EKS cluster.
=> fix: removed unnecessary conditional in private access security group

workers_launch_template_mixed.tf
Fixes a variable lookup against the wrong worker group list introduced by commit c660b6e to add support to set cpu_credits.
=> fix: Incorrect cpu_credit lookup variable (Terraform v0.11)

docs/autoscaling.md
Recently came up in #912. Add a note to our docs about the cluster autoscaler version requirements.
=> docs: autoscaler X.Y version must match

docs/faq.md
Update FAQ with note on how to set a suitable interpreter under Windows.
Fixes #833 
Fixes #925
=> docs: Improve FAQ on how to deploy from Windows

modules/node_groups/README.md, modules/node_groups/node_groups.tf, modules/node_groups/random.tf, modules/node_groups/variables.tf, node_groups.tf
Hack to add a "homemade" depends_on as suggested https://discuss.hashicorp.com/t/tips-howto-implement-module-depends-on-emulation/2305/2 to ensure ordering of ressource creation for managed node groups.
I don't really like the approach, but the hack doesn't add complexity (because, there are only 2 resources in the submodule in which we add an explicit `depends_on`) and seems to work as expected.
I tested it to resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/843
__Note:__ I'm opening this PR to start discussion. So feedbacks are welcomed.
- Is this something we want to do ?
- @dpiddockcmp is your [comment](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/node_groups.tf#L10) still apply ?
=> feat: Add a homemade `depends_on` for MNG submodule to ensure ordering of resource creation

cluster.tf
AmazonEKSClusterPolicy IAM policy doesn't contain all necessary permissions to create ELB service-linked role required during LB provisioning at AWS by K8S Service.
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/900
=> feat: Add IAM permissions for ELB svc-linked role creation by EKS cluster

local.tf
See issue #945 
I added a call to strip out any user given Name tags from `locals.asg_tags` so only the internal Name tags will be applied to asg workers. It looks like this var is only used for two resources, and both of them also try to apply their own Name tags, so there shouldn't be any fallout from dropping it.
=> fix: Strip user Name tag from asg_tags (#945)

README.md, docs/faq.md, outputs.tf
NOTES: Starting in v12.1.0 the `cluster_id` output depends on the
`wait_for_cluster` null resource. This means that initialisation of the
kubernetes provider will be blocked until the cluster is really ready,
if the module is set to manage the aws_auth ConfigMap and user followed
the typical Usage Example. kubernetes resources in the same plan do not
need to depend on anything explicitly.
Try to expand and highlight one of the changes slipped in to v12.1.0.
Fixes #943
=> docs: Better documentation of `cluster_id` output blocking

.github/workflows/lint.yml
Module used by an example does not allow use with 0.13 yet. Lock to latest version of 0.12. No 0.12 floating tag 😞
=> ci: fix CI lint job

local.tf
I feel like people ctrl+f for "key pair", "keypair", "ssh", ... when they look for ways to associate a _key pair_ (that's how AWS calls ssh keys) to worker nodes.
I propose to change the documentation string in local.tf to help users.
=> docs: Describe key_name is about AWS EC2 key pairs

docs/spot-instances.md
Added documentation showing how to run mixed lifecycle instances using launch templates, and dynamically set a label on the node for the lifecycle.
=> docs: Spot instance documentation

README.md, examples/basic/main.tf, examples/create_false/main.tf, examples/irsa/main.tf, examples/launch_templates/main.tf, examples/managed_node_groups/main.tf, examples/secrets_encryption/main.tf, examples/spot_instances/main.tf, variables.tf
Breaking change!
Remove the default value from `cluster_version` making it required.
Stop the rush every time AWS releases a new supported kubernetes version to "upgrade the module". #949 was really a single line change that triggers a major version bump for something a user can set in a variable.
Fixes #947 (sort of)
=> feat: Cluster version is now a required variable.

README.md
This is small change to update `README.md` to reflect a change done during https://github.com/terraform-aws-modules/terraform-aws-eks/pull/972
=> docs: Update about `cluster_version` variable requirement

README.md, cluster.tf, variables.tf
Add `cluster_create_security_group` condition to create the security group rule named `cluster_private_access`
Resolves #980
Resolves #942
=> fix: Create `cluster_private_access` security group rules when it should

README.md
Add notes about the retry logic used by this module to manage the `aws-auth` configmap and the `wget` requirement.
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/829
=> docs: Add important notes about the retry logic and the `wget` requirement

README.md, examples/basic/main.tf, examples/irsa/irsa.tf, examples/irsa/main.tf, examples/launch_templates/main.tf, examples/managed_node_groups/main.tf, examples/secrets_encryption/main.tf, examples/spot_instances/main.tf, versions.tf, workers.tf, workers_launch_template.tf
Terraform v0.13 and aws v3 support time!
- The update to the vpc module was, strictly speaking, unnecessary but it adds the `terraform` block with supported versions.
- Update for iam module was very necessary to support new versions
- Workaround for "Provider produced inconsistent final plan" when creating ASGs at the same time as the cluster. See  https://github.com/terraform-providers/terraform-provider-aws/issues/14085 for full details.
When upgrading an existing TF 0.12/aws 2 cluster to TF 0.13/aws 3 you currently have to manually edit the state file to delete removed attributes. Should be fixed in v0.13.1 https://github.com/hashicorp/terraform/pull/25779 . For the basic example I had to remove the following attributes:
- data `aws_availability_zones`: `blacklisted_names` and …
=> fix: More compatibility fixes for Terraform v0.13 and aws v3

cluster.tf
AWS recently added the ability to assign security groups to pods, more info about this can be found [here](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html). This new feature requires an additional policy attached to the cluster role.
=> feat: Add AmazonEKSVPCResourceController to cluster policy to be able to set AWS Security Groups for pod

docs/iam-permissions.md
For creating VPC endpoints for S3, "ec2:CreateVpcEndpoint" action must also be included in the minimum permission list.
=> docs: Add ec2:CreateVpcEndpoint action to minimum permission list for S3 VPC endpoint

README.md, variables.tf
This PR is addressing issue related to `wait_for_cluster_cmd` check which is defaulting to `wget`. This is brining error if you missing `wget` on local system where you execute Terraform apply. This can be customized via `wait_for_cluster_cmd` but usually people are not following this and meet issue. In past there was few issues opened for this:
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/998
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/829
This PR is changing default `wait_for_cluster_cmd` to contain conditional which is checking `wget` availability, if this is missing then switch to `curl`. This logic should remediate most of issues which users meet (as `wget` is available on most linux distrubution and containers, where `curl` is available out …
=> improvement: update the `wait_for_cluster_cmd` logic to use `curl` if `wget` doesn't exist

local.tf, workers.tf, workers_launch_template.tf
Add `load_balancers`  for clb be associated to asg.
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1036
=> feat: Add `load_balancers` parameter to associate a CLB (Classic Load Balancer) to worker groups ASG

workers_launch_template.tf
If you choose non bustable families in your template (c5 for example...) and you no remove `credit_specification` section, ASG can't start any instance.
Now you can set module `cpu_credits` option to null to made it fonctionnal.
=> improvement: Make the `cpu_credits` optional for workers launch template

cluster.tf
Uses a customer-managed policy, not an inline policy, for the `cluster_elb_sl_role_creation` policy. It is common for "enterprise" AWS users to disallow inline policies with an SCP rule for auditing-related reasons, and this accomplishes the same thing. 
Verified `iam:CreatePolicy` is already listed in `docs/iam-permissions.md`. 
Fixes #1035.
=> fix: Use customer managed policy instead of inline policy for `cluster_elb_sl_role_creation`

cluster.tf
…ter_elb_sl_role_creation"
Fix for #1044 - Path variable is not set for resource "aws_iam_policy" "cluster_elb_sl_role_creation" 
Path variable added to Iam Policy
Resolves #1044 
=> fix: Set IAM Path for `cluster_elb_sl_role_creation` IAM policy

workers.tf, workers_launch_template.tf
When we change workers order (remove the first worker group by example) all workers groups should be destroyed and recreated. This is done correctly for workers ASG, LT and LC, but not their dependencies like random and instance profiles.
```shell
Error: Cycle: module.eks.aws_launch_template.workers_launch_template[1] (destroy), module.eks.random_pet.workers_launch_template[1] (destroy), module.eks.aws_launch_template.workers_launch_template[0] (destroy deposed c013c2bc), module.eks.aws_iam_instance_profile.workers_launch_template[1] (destroy), module.eks.aws_launch_template.workers_launch_template[0], module.eks.random_pet.workers_launch_template[0], module.eks.aws_autoscaling_group.workers_launch_template[0], module.eks.aws_autoscaling_group.workers_launch_template[0] (destroy deposed …
```
=> fix: Fix cycle error during the destroy phase when we change workers order

aws_auth.tf, cluster.tf, local.tf, workers.tf, workers_launch_template.tf
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/568
Supersedes:
- https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1040
- https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1020
=> fix: Use splat syntax to avoid errors during destroy with an empty state

README.md, aws_auth.tf, variables.tf
Add labels to avoid manual mistakes on managed configmap. It adds 2 labels :
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
labels:
app.kubernetes.io/managed-by: Terraform
terraform.io/module: terraform-aws-modules.eks.aws
name: aws-auth
namespace: kube-system
data:
mapAccounts: |
[]
mapRoles: |
........
mapUsers: |
[]
```
By this way and "standard" managed-by label, we know this file is provided and enforced by terraform. You should not edit it manualy.
- [NC] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation
=> feat: Add kubernetes standard labels to avoid manual mistakes on the managed `aws-auth` configmap

.github/workflows/lint.yml
=> ci: Use ubuntu-latest instead of MacOS for docs checks

README.md, outputs.tf
- Problem
- Currently we cannot apply some resources which depends on eks module generated cloudwatch logs **arn**, like followings.
- How to solve?
- add output `cloudwatch_log_group_arn`
```tf
module "eks" {
source = "terraform-aws-modules/eks/aws"
...
}
resource "aws_lambda_permission" "log" {
...
source_arn    = module.eks.cloudwatch_log_group_arn // <- we cannot pass cloudwatch arn in the same terraform apply.
}
```
To work-around, we need to define data resource. But in this case, we need to execute terraform apply twice to get cloudwatch resource.
```tf
data "aws_cloudwatch_log_group" "log" {
name = module.eks.cloudwatch_log_group_name[0]
}
```
=> feat: Add `cloudwatch_log_group_arn` to outputs

README.md, examples/launch_templates_with_managed_node_groups/disk_encryption_policy.tf, examples/launch_templates_with_managed_node_groups/launchtemplate.tf, examples/launch_templates_with_managed_node_groups/main.tf, examples/launch_templates_with_managed_node_groups/templates/userdata.sh.tpl, examples/launch_templates_with_managed_node_groups/variables.tf, local.tf, modules/node_groups/README.md, modules/node_groups/locals.tf, modules/node_groups/node_groups.tf, modules/node_groups/random.tf, versions.tf
fixes #979
Just recently on 17th August, AWS released LaunchTemplate support for managed node-groups. https://aws.amazon.com/blogs/containers/introducing-launch-template-and-custom-ami-support-in-amazon-eks-managed-node-groups/
Furthermore the `aws` provider also supports it since `3.3.0` https://github.com/terraform-providers/terraform-provider-aws/pull/14639
This module didn't support it yet, only LTs for self-managed worker groups.
As the module is quite complex already, I only added support for providing the id of LT you create yourself and then supply the Id.
The existing `workers_launch_template.tf` couldn't have been easily reused imho as its related to also creating ASGs and other resources for self-managed node-groups. Also at least the `iam_instance_profile` should NOT be …
=> feat: LaunchTemplate support for managed node-groups

examples/irsa/README.md, examples/irsa/cluster-autoscaler-chart-values.yaml
This PR fixes two issues in the irsa example:
1. Wrong chart values (or not compatible with the latest version). Please check this line: https://github.com/helm/charts/blob/a5632b118a97e829d9b93312ddc5816c3025d00b/stable/cluster-autoscaler/templates/serviceaccount.yaml#L8
2. Updates the `helm install` command used as the Helm chart has been moved to the kubernetes/autoscaler repository.
=> docs: Update autoscaler installation in IRSA example

docs/faq.md
Adds FAQ section on difference between `node_groups` and `worker_groups` (see #895 and #1077). 
It's based on comments from @dpiddockcmp and others in the issues mentioned before. Let me know if I should clarify something or expand in certain areas. It does answer the question I had when I first encountered this issue.
/ping @barryib
=> docs: Explain node_groups and worker_groups difference in FAQ

docs/spot-instances.md, examples/irsa/README.md, examples/irsa/cluster-autoscaler-chart-values.yaml, examples/irsa/locals.tf
Fixes https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1083, which appears to have been introduced when the cluster-autoscaler helm chart was recently updated to point to [the latest helm repo](https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler-chart), instead of the deprecated one (https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1063). The latest version of the chart deploys a service account named `cluster-autoscaler-aws-cluster-autoscaler-chart` instead of `cluster-autoscaler-aws-cluster-autoscaler`, which causes authentication errors [unless updated](https://github.com/terraform-aws-modules/terraform-aws-eks/compare/master...brannondorsey:irsa-example-latest-helm-repo-fixes?expand=1#diff-fb65fba35892cede42e611ec54263b6eccd3f0 …
=> docs: Fix IRSA example when deploying cluster-autoscaler from the latest kubernetes/autoscaler helm repo

local.tf, modules/node_groups/node_groups.tf
We should define launch_template_id for managed node groups only if it needed.
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1087
=> fix: Change the default `launch_template_id` to `null` for Managed Node Groups

aws_auth.tf, modules/fargate/outputs.tf
The new fargate code seems to have caused a bug in authmap.
Currently even when no fargate profiles are specified the fargate module output is used to create an authmap entry with an empty ARN. 
The plan shows:
```
- "groups":
+   - "system:bootstrappers"
+   - "system:nodes"
+   - "system:node-proxier"
+   "rolearn": ""
+   "username": "system:node:{{SessionName}}"
+ - "groups":
```
Apply errors:
```
Error: Failed to update Config Map: Unauthorized
on .terraform/modules/eks_cluster/aws_auth.tf line 65, in resource "kubernetes_config_map" "aws_auth":
65: resource "kubernetes_config_map" "aws_auth" {
```
This seems to be because "rolearn" is empty.
=> fix: Don’t add empty Roles ARN in aws-auth configmap, specifically when no Fargate profiles are specified

docs/faq.md, examples/managed_node_groups/main.tf
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1089
=> docs: Clarify usage of both AWS-Managed Node Groups and Self-Managed Worker Groups

fargate.tf, modules/fargate/README.md, modules/fargate/fargate.tf, modules/fargate/variables.tf
The iam role created by fargate is missing the `permissions_boundary` attribute
=> feat: Add permissions boundary to fargate execution IAM role

README.md, variables.tf
Make it more obvious that `var.cluster_iam_role_name` will allow reusing an existing iam role for the cluster.
=> docs: Make it more obvious that `var.cluster_iam_role_name` will allow reusing an existing IAM Role for the cluster.

examples/fargate/main.tf, modules/fargate/README.md, modules/fargate/fargate.tf
The EKS cluster can be provisioned with both private and public subnets.
But Fargate only accepts private ones.
This new variable allows to override the subnets to explicitly pass the
private subnets to Fargate and work around that issue.
=> feat: support Fargate in private+public EKS environments

local.tf
Provider has caught up https://github.com/hashicorp/terraform-provider-aws/pull/16652, thanks @ewbankkit 
AWS now has a cheaper and more performant drive type:
https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-new-amazon-ebs-general-purpose-volumes-gp3/
Re: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1130
- [] CI tests are passing
=> feat: Use `gp3` as default as it saves 20% and is more performant

README.md, cluster.tf, variables.tf
This change adds support for service_ipv4_cidr that has been added to terraform-provider-aws last week.
( please see https://github.com/hashicorp/terraform-provider-aws/issues/15505 )
This allows the user to specify the ipv4 CIDR for the k8s services (resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1056 )
=> feat: Add support for `service_ipv4_cidr` for the EKS cluster

.github/CONTRIBUTING.md, README.md, variables.tf
Fixed typos I've noticed while reading the docs.
=> docs: Fix typos in README and CONTRIBUTING

examples/basic/main.tf, examples/irsa/main.tf, examples/launch_templates/main.tf, examples/managed_node_groups/main.tf, examples/secrets_encryption/main.tf
The t2 instance type isn't available in newer regions such as eu-north-1. Therefore the examples using t2 will fail in this region.
Available instance types can be verified with: 
`aws ec2 describe-instance-type-offerings --location-type "region" --region eu-north-1 | jq '.InstanceTypeOfferings[].InstanceType | select(startswith("t"))'`
=> docs: Change instance type from `t2` to `t3` in examples

examples/irsa/irsa.tf, examples/irsa/main.tf, examples/irsa/variables.tf
Bump irsa example deps to versions which work with Terraform 1.4
=> docs: Bump IRSA example dependencies to versions which work with TF 0.14

README.md, local.tf, versions.tf, workers_launch_template.tf
Make it possible to enable nitro enclave support in EKS.
Should resolve (after testing in complete):
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1181
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1182
=> feat: Add nitro enclave support for EKS

.chglog/CHANGELOG.tpl.md, .chglog/config.yml, Makefile
Use custom sort for commit groups and upperFirst function
=> docs: Update changelog generation to use custom sort with git-chglog v0.10.0

local.tf, workers.tf, workers_launch_template.tf
AWS Released lately [ASG Warm Pool](https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-warm-pools.html) feature that will ensure that instances are ready to quickly start serving application traffic, accelerating the response to a scale-out event.
=> feat: Add support for ASG Warm Pools

README.md, cluster.tf, docs/autoscaling.md, irsa.tf, versions.tf, workers.tf, workers_launch_template.tf
Issue - [1320](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1320)
1. Support AWS tags on the following IAM resources
- `aws_iam_policy`
- `aws_iam_instance_profile`
- `aws_iam_openid_connect_provider`
2. Bump required AWS provider version to the `3.35.0`
=> feat: Add tags on additional IAM resources like IAM policies

workers_launch_template.tf
Fix deprecated function `list` and replaced it with `tolist` to work with terraform 0.15
=> fix: list -> tolist for working with terraform v0.15.0

.github/workflows/pre-commit.yml
Update the pre-commit workflow and use terraform-docs 0.13
=> ci: Bump terraform-docs to 0.13

README.md, aws_auth.tf, cluster.tf, docs/faq.md, outputs.tf, variables.tf, versions.tf
In this PR we drop the usage of local-exec. But we need https://github.com/hashicorp/terraform-provider-http/pull/29.
We decided to fork the [terraform-provider-http](https://github.com/hashicorp/terraform-provider-http) provider (the [PR](https://github.com/hashicorp/terraform-provider-http/pull/29) is almost a year) into the [terraform-aws-modules organization](https://github.com/terraform-aws-modules/terraform-provider-http) for internal usage only. The provider is published at https://registry.terraform.io/providers/terraform-aws-modules/http/latest
Related also to https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1253
This is still a proof of concept. I tested it locally and so far so good. I've got this kind of output during my tests.
```shell …
```
=> feat: Replace the local-exec script with a http datasource for waiting cluster

README.md, examples/basic/versions.tf, examples/fargate/versions.tf, examples/irsa/versions.tf, examples/launch_templates/versions.tf, examples/launch_templates_with_managed_node_groups/versions.tf, examples/managed_node_groups/versions.tf, examples/secrets_encryption/versions.tf, examples/spot_instances/versions.tf
Since we now use the terraform-aws-modules/http provider to wait the control plane https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1339, we don't need the null provider anymore.
=> fix: Remove `null` provider from required providers

local.tf, workers.tf, workers_launch_template.tf
This module used random_pet resources to create a random name for the autoscaling group to force the autoscaling group to be re-created when the launch configuration or launch template was changed (if `recreate_asg_when_lc_changes = true` was set), causing the instances to be removed and re-provisioned each time there was an update. Those random_pet resources has been removed and in its place there is now a set of functionality provided by AWS and the Terraform AWS provider - instance_refresh. We encourage those users to move on `instance_refresh`.
Go with https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1224
=> feat: Drop `asg_recreate_on_change` feature to encourage the usage of  Instance Refresh for EC2 Auto Scaling

README.md, versions.tf
Will address https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1339#issuecomment-843226971
cc @nauxliu
=> fix: Bump `terraform-aws-modules/http` provider version to support darwin arm64 release

examples/instance_refresh/main.tf, examples/instance_refresh/outputs.tf
I've updated the example for how to use instance refresh.
- Removed policy attachment to worker security group
- Added spot instance termination support
- Enable lifecycle for all worker groups
- Rename Terraform resources to make it clearer
=> docs: Use IRSA for Node Termination Handler IAM policy attachement in Instance Refresh example

examples/instance_refresh/main.tf, local.tf, workers_launch_template.tf
Set an ASG's launch template version to an explicit version automatically. This will ensure that an instance refresh will be
triggered whenever the launch template changes.
In order to properly trigger instance refresh whenever a launch template is modified the version of the template must be updated in the autoscaling group. Previous versions of this module only supported setting the template version manually. This PR adds a new feature that will either set the version to the latest (real) version or the default (real) version with the use of the boolean `use_latest_version`.  It is still possible to pin a specific  version of template by setting `launch_template_version` in `worker_groups_launch_template`. The default `launch_template_version` is ignored in the case of autoscaling group …
=> fix: set an ASG's launch template version to an explicit version to automatically trigger instance refresh

README.md, versions.tf
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1384
=> fix: Bump `terraform-provider-http` required version to 2.4.1 to avoid TLS Cert Pool issue on Windows

CHANGELOG.md, cluster.tf, data.tf
Add back `depends_on` for `data.wait_for_cluster` which was dropped by error in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1339
=> fix: Add back `depends_on` for `data.wait_for_cluster`

README.md, kubectl.tf, variables.tf
This follows https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1114
BREAKING CHANGES: The  variable `config_output_path` is renamed into `kubeconfig_output_path` for naming consistency. Please upgrade your configuration accordingly.
NOTES: The kubeconfig file permission is not world and group readable anymore. The default permission is now `600`. This value can be changed with the variable `var.kubeconfig_file_permission`.
=> feat: Rename `config_output_path` into `kubeconfig_output_path` for naming consistency

local.tf
=> fix: Default `root_volume_type` must be `gp2`

modules/node_groups/launch_template.tf, workers_launch_template.tf
Revert https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1362
This is a ongoing feature in the terraform-provider-aws. Here the related PR https://github.com/hashicorp/terraform-provider-aws/pull/18033.
Until that PR get merged, I'm reverting this.
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1406
=> fix: Don't add tags on network interfaces because it's not supported yet in `terraform-provider-aws`

README.md, cluster.tf, data.tf
This fix a bug introduced during a merge request conflict resolution in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1274
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1409
=> fix: Remove duplicated security group rule for EKS private access endpoint

local.tf
Supersedes https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1411
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1410
=> fix: Fix AMI filtering when the default platform is provided in `var.workers_group_defaults`

docs/iam-permissions.md
docs(iam): add 'iam:TagOpenIDConnectProvider' to list of necessary permissions
Minor docs update.
* adds 'iam:TagOpenIDConnectProvider' to list of necessary permissions
* might be worth considering to add `'iam:Tag*`?
This caused a permission error with IRSA enabled with this EKS module. Hope to prevent this for others in the future :)
- don't think this applies as this is a pure and very minor docs update
=> docs: Add `iam:TagOpenIDConnectProvider` to list of necessary permissions

local.tf, workers.tf, workers_launch_template.tf
- See https://docs.aws.amazon.com/autoscaling/ec2/userguide/capacity-rebalance.html. We already have most functionality, only this parameter is missing
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1124
=> feat: Add `capacity_rebalance` support for self-managed worker groups

examples/managed_node_groups/main.tf, modules/node_groups/README.md, modules/node_groups/locals.tf, modules/node_groups/node_groups.tf, modules/node_groups/versions.tf
Add support for set taints on managed node groups, Resolve #1403
Ref:
https://docs.aws.amazon.com/eks/latest/userguide/node-taints-managed-node-groups.html
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#taint-configuration-block
=> feat: Add support for Managed Node Groups (`node_groups`) taints

irsa.tf, local.tf
* rename client_id_list local variable
* add distinct() func
The changes made as a result of the discussion in the #1451.
=> chore: Update client_id_list argument for OIDC provider

templates/userdata_windows.tpl
Put KubeletExtraArgs in double quotes for Windows, it is already double quoted in the Bash script. This allows for variable substitution within the string e.g.
```
kubelet_extra_args = "node.kubernetes.io/lifecycle=$(Invoke-WebRequest -Uri http://169.254.169.254/latest/meta-data/instance-life-cycle | Select-Object -ExpandProperty Content)"
```
=> fix: Put KubeletExtraArgs in double quotes for Windows

README.md, examples/managed_node_groups/versions.tf, modules/node_groups/README.md, modules/node_groups/versions.tf, versions.tf
=> fix: Updated required version of AWS provider to 3.56.0

examples/launch_templates_with_managed_node_groups/launchtemplate.tf, modules/node_groups/launch_template.tf, workers_launch_template.tf
The PR should resolve: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1361
=> feat: Add ability to tag network-interface using Launch Template

cluster.tf, modules/node_groups/launch_template.tf
Currently when you enable create_launch_template=true on the nodegroup, it switches from using primary cluster security group to worker security group which can cause various problems.
The first work around attempted was to use cluster_primary_security_group_id as worker_security_group_id, but that caused variable cycle error.
```
Error: Cycle: module.eks.local.cluster_primary_security_group_id (expand), module.eks.output.cluster_primary_security_group_id (expand), module.eks.var.worker_security_group_id (expand), module.eks.local.worker_security_group_id (expand), module.eks.aws_security_group_rule.cluster_https_worker_ingress, module.eks.aws_eks_cluster.this
```
The second workaround was to add the primary security group as worker_additional_security_group_ids, however that causes the …
=> fix: worker security group handling when worker_create_security_group=false

cluster.tf
Create separate sg rule for each new `cluster_endpoint_private_access_cidr` block in order to fix **A duplicate Security Group rule error** mentioned in #984 
At the moment, it isn't possible to update the `cluster_endpoint_private_access_cidrs` variable since terraform apply fails with the error described in the #984 
Initial settings:
```
module "eks" {
source = "github.com/terraform-aws-modules/terraform-aws-eks.git?ref=v17.3.0"
...
cluster_endpoint_private_access                           = true
cluster_endpoint_private_access_cidrs                 = ["104.145.4.34/32"]
cluster_create_endpoint_private_access_sg_rule = true
```
Updated settings:
```
module "eks" {
source = "github.com/terraform-aws-modules/terraform-aws-eks.git?ref=v17.3.0"
...
cluster_endpoint_private_access …
```
=> feat: Create SG rule for each new cluster_endpoint_private_access_cidr block

README.md, main.tf, variables.tf
Our intent is to update our exising EKS cluster with `cluster_encryption_config` as it was introduced here:
- https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-eks-supports-adding-kms-envelope-encryption-to-existing-clusters/?nc1=h_ls
- https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#enable-kms
- https://aws.amazon.com/de/blogs/containers/using-eks-encryption-provider-support-for-defense-in-depth/
Unfortunately updating the cluster with `cluster_encryption_config` consumes more than 1h (at least in euc1).
As a default I used what's default in the resource `aws_eks_cluster`: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#timeouts
=> feat: Ability to specify cluster update timeout

docs/faq.md
`asg_recreate_on_change` feature was dropped here : https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1360
Update faq
=> docs: Remove `asg_recreate_on_change` in faq

examples/launch_templates_with_managed_node_groups/disk_encryption_policy.tf, examples/launch_templates_with_managed_node_groups/launchtemplate.tf, examples/launch_templates_with_managed_node_groups/main.tf, examples/launch_templates_with_managed_node_groups/variables.tf
remove `instance_type` in `aws_launch_template.default` to avoid this error:
```
│ Error: error creating EKS Node Group (test-eks-lt-URZJOIL1:test-eks-lt-URZJOIL1-example2021092307395969650000000f): InvalidRequestException: Cannot specify instance types in launch template and API request
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "bece44af-e7e0-4931-9725-4fb57a7de031"
│   },
│   ClusterName: "test-eks-lt-URZJOIL1",
│   Message_: "Cannot specify instance types in launch template and API request",
│   NodegroupName: "test-eks-lt-URZJOIL1-example2021092307395969650000000f"
│ }
│
│   with module.eks.module.node_groups.aws_eks_node_group.workers["example"],
│   on ../../modules/node_groups/main.tf line 1, in resource "aws_eks_node_group" "workers":
│    1: resource …
```
=> fix: Fixed launch_templates_with_managed_node_group example

README.md
Fixed typo I've noticed while using the docs.
=> docs: Fix broken URL in README

docs/faq.md, docs/spot-instances.md, docs/upgrades.md
Resolves #1111
Duplicate of https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1592
Additionally fixing some markdown formatting issues
=> docs: update faq about endpoints

docs/faq.md
This explaining why changing desired capacity in node and worker groups doesnt take effect for this module.
Resolves #1568 #835
=> docs: Updated faq about desired count of instances in node and worker groups

modules/node_groups/README.md, modules/node_groups/launch_template.tf, modules/node_groups/locals.tf, modules/node_groups/templates/userdata.sh.tpl
This PR could replace https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1433.
The managed node group bootstrap pattern has been modified to set the `/etc/eks/bootstap.sh` environment variables to control the bootstrap process. To do this a new `bootstrap_env` variable has been added which sets env variables to be sourced into `/etc/eks/bootstrap.sh` from a new `/etc/profile.d/eks-bootstrap.sh` file. For power users `pre_userdata` can append additional values or dynamic functionality to this file.
=> feat: Improve managed node group bootstrap revisited

examples/complete/main.tf, examples/fargate/main.tf, modules/fargate/README.md, modules/fargate/main.tf
Add ability to define custom timeout for create/delete operations for fargate profiles
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1610
=> feat: Add ability to define custom timeout for fargate profiles

README.md, variables.tf
EKS AWS API accept only specifying a Minor Kubernetes version
Resolves #1669
Kubernetes version policy https://kubernetes.io/releases/version-skew-policy/
=> chore: update `cluster_version` description

modules/node_groups/README.md, modules/node_groups/main.tf, modules/node_groups/variables.tf, node_groups.tf
removing legacies related to pre terraform 0.13 hack dependencies between modules. I have tested 2 examples in following combination:
1. apply from scratch
2. modify config and reapply
3. destroy example
in each case it was working without issues. Also this is transparent change to existing clusters (just refresh on state is happening)
resolves #1574
=> feat: Removed ng_depends_on variable and related hack

.github/workflows/release.yml, .pre-commit-config.yaml, .releaserc.json
- update preset rule on semantic-release to use conventional commits
Note: this should re-scan the commit since the last release and pick up the breaking `feat!` change causing v18.x to be released
- current release process is not triggering a breaking change release due to using default `angular` preset
- no
- https://github.com/clowdhaus/terraform-release-test/releases
=> fix: Update preset rule on semantic-release to use conventional commits

examples/eks_managed_node_group/main.tf, modules/eks-managed-node-group/main.tf
Currently if user specifies `remote_access` in `eks_managed_node_groups`, terraform will throw an error since we iterate the `remote_access` object directly, which is not expected.
=> fix: Not to iterate over remote_access object in dynamic block

node_groups.tf
Use var.prefix_separator for the node security group prefix like in the cluster security group prefix
so it is consistent with the cluster security group
no
=> fix: Use the prefix_seperator var for node sg prefix

README.md, examples/eks_managed_node_group/README.md, examples/eks_managed_node_group/main.tf, modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/variables.tf
- fix vpc remote access variable for security groups to allow for list of security groups; closes #1762 
- update `eks-managed-node-group` to demonstrate shortcomings of additional IAM policies and security groups, providing an explanation and example for how best to utilize these due to https://github.com/hashicorp/terraform/issues/4149
- note added to main README to alert and educate users on this issue
- Ref https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1753#issuecomment-1010146823
- Closes #1762 
- documentation for users on how to use additional resources within the module
- No
- Validate with `eks-managed-node-group` example
=> fix: Correct remote access variable for security groups and add example for additional IAM policies

examples/user_data/main.tf, modules/_user_data/README.md, modules/_user_data/main.tf
- update user data docs to correct mistake of showing `bootstrap_extra_args` when prepending user data (default AMI)
- Closes #1770
- No
- user data and eks managed node group examples
=> chore: Update user data docs to correct mistake of showing `bootstrap_extra_args` when prepending user data (default AMI)

UPGRADE-18.0.md
- Add a specific before / after example for using `fargate_profiles`
I ran into a situation where I wasn't sure how to use the new `fargate_profiles` output so based on https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1777 @bryantbiggs and I determined adding additional examples to the upgrade guide was worth it to make it easier for folks to upgrade from 17.x to 18.x.
None.
It's Markdown documentation.
=> docs: Add use case examples to the 18.x upgrade guide

examples/eks_managed_node_group/main.tf, examples/self_managed_node_group/main.tf, node_groups.tf
- change `instance_metadata_tags` to default to `null`/`disabled` due to tag key pattern conflict
- Closes #1785 
- The default is `disabled` when a value is not provided. In hindsight, we should have matched the default behavior of the API and let users opt in. I don't know why there is a different tag restriction pattern for metadata tags but its currently causing issues for users so better to opt out and let them opt in as they see fit
- Controversial, but I will say no
=> fix: Change `instance_metadata_tags` to default to `null`/`disabled` due to tag key pattern conflict

README.md, examples/complete/main.tf, examples/eks_managed_node_group/main.tf, examples/self_managed_node_group/main.tf
- add example usage of extending cluster and node security group access rules
- Closes #1790 
- This should provide more example usage to users to demonstrate how to extend the security group access for the baseline that is provided
- No
- Update examples and tested on `complete` example
=> chore: Add example usage of extending cluster and node security group access rules

examples/self_managed_node_group/main.tf, node_groups.tf
- add missing `mixed_instances_policy` parameter to the root module
- Closes #1807
- No
- Updated `self-managed-node-group` example for testing and validation
=> fix: Add missing `mixed_instances_policy` parameter to the root module

node_groups.tf
* Add missing `launch_template_use_name_prefix` parameter to the root module
* Currently `self-managed-node-group`'s `launch_template_use_name_prefix` variable is not passed to the module, this PR is intended to solve this
* Tested by using the `self-managed-node-group` sub-module with `launch_template_use_name_prefix` set to `True`/`False` and verifying that `aws_launch_template` resource's `name_prefix`/`name` arguments are being set accordingly and the launch template is created as expected
=> fix: Add missing `launch_template_use_name_prefix` parameter to the root module

examples/eks_managed_node_group/README.md, examples/eks_managed_node_group/main.tf, examples/self_managed_node_group/README.md, examples/self_managed_node_group/main.tf, modules/eks-managed-node-group/main.tf
- correct issue where custom launch template is not used when EKS managed node group is used externally
- update documentation and provide example of utilizing `containerd` runtime on EKS managed node group
- update static AMI IDs in examples to use data source; ensures the current AMI is always pulled when testing
- minor formatting for correct use of EOT and left aligning text
- Closes #1816
- There have been a number of questions regarding the EKS managed node group user data and configuring the bootstrap process (specifically around enabling the containerd runtime) and hopefully this helps clear things up for users
- No
- Using the `eks-managed-node-group` example
- `eks-manged-node-group` example was deployed as its defined today
- Added in sub-module snippet provided in issue here …
=> fix: Correct issue where custom launch template is not used when EKS managed node group is used externally

examples/complete/main.tf, modules/eks-managed-node-group/main.tf, modules/self-managed-node-group/main.tf
- `block_duration_minutes` under launch template `spot_options` is not a required attribute
- Fix `compelte` example, external EKS managed node group module which was missing the security group IDs and failing to join the cluster
- This was a bug found when investigating #1844
- No
=> fix: The `block_duration_minutes` attribute under launch template `spot_options` is not a required

README.md, examples/complete/main.tf, examples/eks_managed_node_group/main.tf, examples/fargate_profile/main.tf, examples/irsa_autoscale_refresh/main.tf, examples/self_managed_node_group/main.tf, variables.tf
- Enable IRSA by default
- Within the EKS ecosystem, it is difficult to find a scenario where the EKS OIDC provider (IRSA) should not be enabled
- No - users who wish to opt out of IRSA enablement can set `enable_irsa = false`
=> feat: IRSA enabled by default

main.tf
- Add node group dependency for EKS addons resource creation
- Added note regarding future addons that may need to be provisioned ahead of node groups; we can add a separate resource for those addons or re-visit if the lifecycle of addons has been fixed upstream. However, for now I think we can live with this change without much issue
- Closes #1801
- No
- Tested with `eks-managed-node-group` example
=> fix: Add node group dependency for EKS addons resource creation

node_groups.tf
- Allow conditional creation of self_managed_node_group by passing the variable "create" to the module
- If "create" is not present the default value "true" is used
- If "create" is set to "false" the module is not created
We are using the same manifest for different stages. Some resources are created conditionally based on variables set for a specific stage. We defined multiple self managed node groups in the map self_managed_node_group, but not all of them are relevant for all stages. We would like to be able to create some of the entries conditionally on the "create" variable defined by the self_managed_node_group submodule.
- No
I tested three different scenarios
1.  create = true -> The self_managed_node_group was created with all its resources
2. create = false -> The …
=> feat: Allow conditional creation of node groups to be set within node group definitions

node_groups.tf
- use existing node security group when one is provided
- Closes #1859 
- No
=> fix: Use existing node security group when one is provided

.pre-commit-config.yaml, README.md, examples/complete/README.md, examples/complete/outputs.tf, examples/eks_managed_node_group/README.md, examples/eks_managed_node_group/outputs.tf, examples/fargate_profile/README.md, examples/fargate_profile/outputs.tf, examples/irsa_autoscale_refresh/README.md, examples/irsa_autoscale_refresh/outputs.tf, examples/self_managed_node_group/README.md, examples/self_managed_node_group/outputs.tf, outputs.tf
- Add additional output for OIDC provider (issuer URL without leading `https://`)
- Avoid duplicating logic of stripping leading `https://` in multiple places and match what is shown in the console. If you log into the console and navigate to IAM -> Identity providers -> select an OIDC provider, in the top left under `Summary` you will see this same value stored under the field `Provider`; hence the output name here is simply `oidc_provider`
- No
=> feat: Add additional output for OIDC provider (issuer URL without leading `https://`)

.pre-commit-config.yaml, examples/irsa_autoscale_refresh/main.tf, modules/self-managed-node-group/README.md, modules/self-managed-node-group/main.tf, modules/self-managed-node-group/variables.tf, node_groups.tf
- Update autoscaling group `tags` -> `tag` to support v4 of AWS provider. This is now a dynamic `tag` block and the current functionality has been preserved through a map comprehension statement. The variable `var.propagate_tags` has been removed as part of this change and users should pass any tags through the normal `var.tags` variable now
- Closes #1874 
- Avoids showing users a deprecation statement for `tags` on autoscaling group
- `var.propagate_tags` is removed and `var.tags` is used in its place so I am (controversially) electing to not mark this as a breaking change (does not affect a significant population of users and there is a clear path to mitigate without state changes or downtime)
=> fix: Update autoscaling group `tags` -> `tag` to support v4 of AWS provider

modules/self-managed-node-group/main.tf
Adds missing quotes to the `block_duration_minutes` value in `spot_options`. 
Without these quotes terraform will think it's a resource and will throw an `Invalid reference` error : 
```
│ Error: Invalid reference
│ 
│   on .terraform/modules/reactive_cluster.eks.eks/modules/self-managed-node-group/main.tf line 161, in resource "aws_launch_template" "this":
│  161:           block_duration_minutes         = lookup(spot_options.value, block_duration_minutes, null)
│ 
│ A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
```
None
=> fix: Add missing quotes to block_duration_minutes

README.md, examples/eks_managed_node_group/README.md, examples/eks_managed_node_group/main.tf, examples/irsa_autoscale_refresh/README.md, examples/irsa_autoscale_refresh/charts.tf, main.tf
- Update examples to show integration and usage of new IRSA role submodules
- Correct one instance of hard coded AWS DNS suffix to use AWS partition data source
- Better inform users how to use new IRSA module that integrates with this module
- No
=> fix: Update examples to show integration and usage of new IRSA submodule

main.tf
- Ensure that cluster encryption policy resources are only relevant when creating the IAM role
- Bug introduced on #1915 where the create role check was not added to the new policy & attachment so v18.8.0 is trying to attach a policy to a non-existent role when users are providing their own cluster role
- No
=> fix: Ensure that cluster encryption policy resources are only relevant when creating the IAM role

README.md, main.tf
- Compact result of cluster security group to avoid disruptive updates when no security groups are supplied
- Closes #1892
- Relates to #1911
- Closes #1921
- Relates to #1933
- No
=> fix: Compact result of cluster security group to avoid disruptive updates when no security groups are supplied

modules/eks-managed-node-group/outputs.tf, modules/fargate-profile/outputs.tf, modules/self-managed-node-group/outputs.tf, outputs.tf
When sub-module generate outputs, it needs to consider if the worker instance is using custom iam role, if so, it should directly output the variable associated with it. otherwise, it will return empty string cause damage to the cluster if not carefully use these outputs.
when we patch the aws_auth config following https://github.com/terraform-aws-modules/terraform-aws-eks/blob/9a99689cc13147f4afc426b34ba009875a28614e/examples/complete/main.tf#L301-L336.  
we found out that rolearn from `module.eks.aws_auth_configmap_yaml` was empty
```
kubectl -n kube-system describe configmap/aws-auth
Name:         aws-auth
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>
Data
====
mapRoles:
----
- rolearn:
username: system:node:{{EC2PrivateDNSName}}
groups:
- system:bootstrappers
- …
```
=> fix: Sub-modules output the correct eks worker iam arn when workers utilize custom iam role

node_groups.tf
- Allow users to specify default launch template name in node groups
- Closes #1945 
- No
=> feat: Allow users to specify default launch template name in node groups

README.md, main.tf
- Add tags to EKS created cluster security group to match rest of module tagging scheme
- I discovered that cluster tags are not propagated to the security group created by the EKS service https://github.com/aws/karpenter/pull/1332/files#diff-c996548a210a321770151def6b6f02b6204a8bcdda9a1e1d86973fa3fbda5e18R145-R152 - this will now add those tags similar to the scheme used on the cluster definition itself
- No
- Tested on `complete` example
=> feat: Add tags to EKS created cluster security group to match rest of module tagging scheme

README.md, examples/complete/main.tf, main.tf, node_groups.tf, outputs.tf
- Default to cluster version for EKS and self managed node groups when a `cluster_version` is not specified
- Add `cluster_version` output for users to use when using separate node group sub-modules (see updated `complete` example)
- Correct doc change for Karpenter IRSA example
- Relates to #1959
- Relates to #1960
- Closes #1962
- The `version` on the EKS cluster resource is optional and will default to the latest Kubernetes version supported by EKS. However, if a version is not specified in the root module via `var.cluster_version`, then a version is not propagated to the sub-modules which can result in an error. By changing from the `var.cluster_version` to the EKS cluster resource output of `version` and using that as the default, we are able to achieve the same functionality when …
=> fix: Default to cluster version for EKS and self managed node groups when a `cluster_version` is not specified

README.md, examples/eks_managed_node_group/main.tf, modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/versions.tf, modules/self-managed-node-group/README.md, modules/self-managed-node-group/versions.tf, versions.tf
- Update TLS provider to require at least v3.0; there are no code changes required for this
- Remove unnecessary cloud init version requirements in the EKS managed node group and self managed node group modules; the version is constrained in the user data module which both of those module use, rendering their requirements redundant
- Keep providers up to date and clean up redundant requirements
- No
- Tested on `eks-managed-node-group` example
=> feat: Update TLS provider and remove unnecessary cloud init version requirements

examples/complete/main.tf, modules/self-managed-node-group/README.md, modules/self-managed-node-group/main.tf, modules/self-managed-node-group/variables.tf, node_groups.tf
* Add new attribute `use_default_tags` to EKS self managed node group module definition. When set to `true`, the default tags configured on the provider will be added to the autoscaling_group tags.
* Update the root module to look at `var.self_managed_node_groups` or `var.self_managed_node_group_defaults` and pass the result to the self managed node group module.
Fixes #1916 
No
- [✅ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [✅ ] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [✅ ] I have executed `pre-commit run -a` on my pull request
=> feat: Support default_tags in aws_autoscaling_group

main.tf
- Add back in CloudWatch log group create deny policy to cluster IAM role. A note has been added and reference to original issue to better explain the issue that is being solved
- Relates to a prior issue https://github.com/terraform-aws-modules/terraform-aws-eks/issues/920 and uses a similar solution https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1594
- No; to users the change will be functionally transparent but will show up in the next subsequent plan (if their use case creates an IAM role and CloudWatch log group)
- Already in place
- Validated with `examples/eks_managed_node_group`
=> feat: Add back in CloudWatch log group create deny policy to cluster IAM role

.pre-commit-config.yaml, examples/self_managed_node_group/README.md, examples/self_managed_node_group/main.tf, modules/eks-managed-node-group/main.tf, modules/self-managed-node-group/main.tf
- Correct `capacity_reservation_target` within launch templates of both EKS and self managed node groups
- Closes #1897
- Closes #1898
- No
=> fix: Correct `capacity_reservation_target` within launch templates of both EKS and self managed node groups

.pre-commit-config.yaml, examples/self_managed_node_group/main.tf, modules/eks-managed-node-group/main.tf, modules/self-managed-node-group/main.tf
- Add support for allowing EFA network interfaces; no 
- Additional interface attributes were not added due to requiring v4 of provider - will come later at next breaking change
- Closes #1880
- Closes #1907
- No
=> feat: Add support for allowing EFA network interfaces

main.tf, modules/eks-managed-node-group/main.tf, modules/self-managed-node-group/main.tf, node_groups.tf
- Add `create_before_destroy` lifecycle hook to security groups created
- This came up in testing how to remove the node group specific security group that is mostly unused by users. When trying to set `create_security_group` to `false` after it defaults to `true` and has been created, the security group is unable to detach and delete. Reading through the numerous issues, I am hopeful this might work for the autoscaling groups. If not, it should be in place regardless for when users re-name their security groups and they need to be re-created
- No
=> feat: Add `create_before_destroy` lifecycle hook to security groups created

examples/eks_managed_node_group/main.tf, main.tf
- Avoid re-naming the primary security group through a `Name` tag and leave to the EKS service to manage
- Closes #2006
- Closes #2008
- No
=> fix: Avoid re-naming the primary security group through a `Name` tag and leave to the EKS service to manage

outputs.tf
- Add `compact()` to `aws_auth_configmap_yaml` for when node groups are set to `create = false`
- Closes #1970 
- No
=> fix: Add `compact()` to `aws_auth_configmap_yaml` for when node groups are set to `create = false`

main.tf
This is a supplement fix for
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1904
This MR is a combined fix for succefully launching Karpenter 0.8.2 on AWS EKS on China Region (cn-northwest-1)
N/A
- [*] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
AWS EKS version 1.22 + Karpenter 0.8.2 launched succefully with this fix with node scaling test done.
=> fix: Correct DNS suffix for OIDC provider

examples/karpenter/README.md, examples/karpenter/main.tf
This example change comes along with https://github.com/terraform-aws-modules/terraform-aws-iam/pull/235
Offered an example file that works for partition such as aws-gov and aws-cn
N/A
- [*] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
With combined MRs, an eks cluster with kapenter 0.8.2 is successfully launched on cn-northwest-1 region.
=> chore: Update Karpenter example to use partition data source

modules/self-managed-node-group/README.md, modules/self-managed-node-group/main.tf, modules/self-managed-node-group/outputs.tf, modules/self-managed-node-group/variables.tf, node_groups.tf
adds  `create_autoscaling_group` to `self-managed-node-groups` and adds `image_id` and `user_data` outputs. 
Currently to use this module with something like karpenter or spotinst you need to create a nodegroup and scale it down in order to have the iam role, userdata, etc. created for you.
You can then do something like this to get all the data you need:
```
data "aws_autoscaling_group" "spotinst" {
name = module.eks.self_managed_node_groups["spotinst"].autoscaling_group_name
}
data "aws_launch_configuration" "spotinst" {
name = data.aws_autoscaling_group.spotinst.launch_configuration
}
iam_instance_profile  = data.aws_launch_configuration.spotinst.iam_instance_profile
security_groups       = data.aws_launch_configuration.spotinst.security_groups
image_id              = …
```
=> feat: Add `create_autoscaling_group` option and extra outputs

main.tf, outputs.tf
Apply distinct() on role arns to ensure no duplicated roles in aws auth configmap
1. Created a cluster with a couple of eks managed node groups which shared the same iam role names
```hcl
module "eks" {
source  = "terraform-aws-modules/eks/aws"
version = "~> 18.21"
eks_managed_node_groups = {
"dummy_cpu" = {
"ami_type" = "AL2_x86_64"
"desired_size" = 1
"instance_types" = [
"t3.small",
]
"max_size" = 1
"min_size" = 0
}
"dummy_gpu" = {
"ami_type" = "AL2_x86_64_GPU"
"desired_size" = 0
"instance_types" = [
"g4dn.xlarge",
]
"max_size" = 1
"min_size" = 0
"taints" = [
{
"effect" = "NO_SCHEDULE"
"key" = "nvidia.com/gpu"
"value" = "true"
},
]
}
"dummy_testapp_cpu" = {
"ami_type" = "AL2_x86_64"
"desired_size" = 1
"instance_types" = [
"t3.small",
]
"max_size" = 1
"min_size" = 0
}
"platform" = { …
```
=> feat: Apply `distinct()` on role arns to ensure no duplicated roles in aws-auth configmap

examples/self_managed_node_group/main.tf, modules/self-managed-node-group/README.md, modules/self-managed-node-group/main.tf, modules/self-managed-node-group/variables.tf, node_groups.tf
`cluster-autoscaler` discovers ASGs using tags, which could currently only be set by setting tags on all resources. This helps setting tags like `k8s.io/cluster-autoscaler/enabled` on the `aws_autoscaling_group` resources only.
Fixes #2072 
None
=> feat: Add `autoscaling_group_tags` variable to self-managed-node-groups

modules/eks-managed-node-group/README.md
Improving the docs a little bit, I was bitten hard by the lack of guidance on those two variables.
Gives the information to anyone that tries to decouple the main `eks` module to different managed or self-managed groups.
None. Docs only.
=> docs: Mention that security groups must be manually referenced on externally attached EKS managed groups

examples/eks_managed_node_group/README.md, examples/eks_managed_node_group/main.tf, modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/outputs.tf
Added node group labels and taints to the outputs of the eks_managed_node_group module.
Re-outputting the labels and taints for the node group as convenience outputs allows for easier use, especially in the case where the autoscaling group must be tagged with label and taint information (such as cluster-autoscaler scaling up from 0).
Satisfies #2104 
None
- [-] I have executed `pre-commit run -a` on my pull request
I updated the eks_managed_node_group example to use the labels and taints to create ASG tags for cluster autoscaler scale from 0.
=> feat: Add node group labels and taints to module outputs

main.tf
- Remove `modified_at` from ignored changes on EKS addons
- Closes #2081 
- Deploying the `complete` example using version 1.1.5 I am not seeing the changes in the plans as before. However, while forcing a minimum required version of 1.2.0 would be a breaking change, simply removing the ignored changes is not a breaking change. Either route (keep the ignored changes or remove) has the potential to show something in the plans/applies so why not remove it in favor of using the later versions of Terraform which doesn't incur a breaking change penalty 
- No
=> fix: Remove `modified_at` from ignored changes on EKS addons

main.tf
Fix a reference for EKS service role.
It should be a link to EKS service IAM role, not a IAM role for node groups
It is confusing.
No breaking changes. Just fixing a comment.
=> docs: Update link for EKS service role

README.md, main.tf
- Update KMS module version which aligns on module version requirements. Version v1.0.1 of the KMS module supports the version of Terraform and AWS provider in this module; in v1.0.0 the versions were Terraform >= 1.0 and AWS provider >= 4.0 which forced users into later version requirements
- Closes #2126
- Closes #2130 
- No
=> fix: Update KMS module version which aligns on module version requirements

node_groups.tf
- Correct Fargate profiles additional IAM role policies default type to match variable
- Closes #2136
- Closes #2142 
- No
=> fix: Correct Fargate profiles additional IAM role policies default type to match variable

examples/eks_managed_node_group/README.md
Update EKS Managed Node Groups example's README to address some typos.
None
=> docs: EKS Managed Node Groups example typo

node_groups.tf
Description
Minor fix allowing partition changes [as per main.tf](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/5955d26589979abdad832e4e9a2dec9753ebc738/main.tf#L227).
Motivation and Context
Failed when using a different partition.
Breaking Changes
No.
How Has This Been Tested?
Unsure how to test it in example context. Require differing partitions.
Corrected to match suggestion from [previous PR](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2146). I've run the code against my scenario and it worked fine.
=> fix: Use partition data source on VPC CNI IPv6 policy 

.pre-commit-config.yaml, README.md, examples/eks_managed_node_group/README.md, examples/eks_managed_node_group/versions.tf, examples/self_managed_node_group/README.md, examples/self_managed_node_group/versions.tf, main.tf, versions.tf
- Pin TLS provider version to 3.x versions only
- Correct KMS key creation boolean logic
- Ref https://github.com/hashicorp/terraform-provider-tls/issues/244
- Closes #2170 
- Closes #2171
- Closes #2172
- Closes #2173 
- No
=> fix: Pin TLS provider version to 3.x versions only

outputs.tf
- Remove empty `""` from node group names output when node group creation is disabled
- Closes #2193 
- No
=> fix: Remove empty `""` from node group names output when node group creation is disabled

README.md, examples/eks_managed_node_group/README.md, examples/eks_managed_node_group/versions.tf, examples/self_managed_node_group/README.md, examples/self_managed_node_group/versions.tf, versions.tf
In #2174 the tls provider was pinned to `~> 3.0` because of https://github.com/hashicorp/terraform-provider-tls/issues/244,
of which the corresponding problem was fixed in 4.0.1 of the provider according to the maintainer, which I can confirm.
This PR will upgrade the tls provider to the version which includes the fix.
This is required, since we should look forward to being as up to date as possible and to prohibit any provider errors, because
a lot of modules have already upgraded to 4x.
None, that I can think of.
=> feat: Allow TLS provider to use versions 3.0+ (i.e. - `>= 3.0`)

modules/self-managed-node-group/outputs.tf
Fixes issue #2235 ; configure the output of image id to be the real output of the launch_template
#2235 
If a user provided a custom ami_id and relied on the broken information this submodule was returning, they could see a change in behavior as the output corrects itself.
- `examples/self_managed_node_group`
- Run: `terraform output -json | jq .self_managed_node_groups.value.bottlerocket.image_id`
- Value before change: `ami-0f2b7c6874eb8414f` (The default AMI, despite being overridden in the config)
- Value after change: `ami-04958b57e72e69fb0` (The actual bottlerocket ami id)
=> fix: Set `image_id` to come from the launch template instead of data source for self-managed node groups

README.md, examples/complete/README.md, examples/complete/outputs.tf, examples/eks_managed_node_group/README.md, examples/eks_managed_node_group/outputs.tf, examples/fargate_profile/README.md, examples/fargate_profile/outputs.tf, examples/karpenter/README.md, examples/karpenter/outputs.tf, examples/self_managed_node_group/README.md, examples/self_managed_node_group/outputs.tf, main.tf, modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/variables.tf, outputs.tf
- Add output for cluster TLS certificate SHA1 fingerprint
- Add provider default tags to EKS created security group for tag stability
- Update user data variable description to clarify its usage with `ami_id`
- Resolves #2227 
- Resolves #2214
- No
=> feat: Add output for cluster TLS certificate SHA1 fingerprint and provider tags to cluster primary security group

.pre-commit-config.yaml, main.tf
- Replace CloudWatch log group ARN in cluster IAM role policy to use a `"*"` instead
- The current solution scoped to the CloudWatch log group ARN does not work as intended but the wildcard `"*"` version does. See thread at end of this prior issue where the issue still persists on latest version of module https://github.com/terraform-aws-modules/terraform-aws-eks/issues/920
- No
=> fix: Update CloudWatch log group creation deny policy to use wildcard

docs/faq.md, examples/fargate_profile/README.md, examples/fargate_profile/main.tf, examples/fargate_profile/versions.tf, main.tf
- Disable creation of cluster security group rules that map to node security group when `create_node_security_group` = `false`
- Update Fargate example to run only Fargate and show disabling of both cluster and node security groups
- Resolves #2258 
- No
=> fix: Disable creation of cluster security group rules that map to node security group when `create_node_security_group` = `false`

examples/complete/main.tf
- Remove usage of default tags in `complete` example since support will be removed in v19 due to a number of issues
- Comment out `cluster_identity_providers` in `complete` example - deploying the example as is results in an issue where both Fargate profiles are trying to be created at the same time as the additional cluster identity provider. These operations need to be made independently
- Update `complete` example to show that the IAM role created by node groups/profiles need to be added back into the core module in order to be added to the aws-auth configmap
- Add example of additional Bottlerocket user data via `bootstrap_extra_args` for standalone EKS managed node group
- Resolves #2289
- Resolves #2290
- No
=> chore: Update examples to better demonstrate questions raised through issues

main.tf
Include all certificate fingerprints in the thumbprint list, rather than just the first one
I'm following the Terraform documentation for enabling IRSA https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#enabling-iam-roles-for-service-accounts. This suggests that all the certificates thumbprints should be listed. This module currently only selects the first one, which should be the highest root certificate in the chain pulled back by the `tls_certificate` data lookup. I can't see anything to suggest that this is intentional.
No breaking changes
I only have access to my work environment. I have tested this change against our development and staging environments without issues.
=> fix: Include all certificate fingerprints in the OIDC provider thumbprint list

modules/karpenter/main.tf
- Ensure that `var.create` is tied to all resources correctly
- Resolves #2306 
- No
=> fix: Ensure that `var.create` is tied to all resources correctly

examples/complete/main.tf, main.tf, node_groups.tf
fixed typo in nested lookup() calls in `aws_security_group_rule.cluster` resource
If a security group ID is supplied in the `source_security_group_id` parameter to `cluster_security_group_additional_rules`, the ternary operator will break, as the nested lookup() function will return a string rather than a bool.
No breaking changes.
Change was tested on production code within our organisation, which creates a SG rule with an external SG as its source. The same input worked under v18 and broke under v19.
=> fix: Call to lookup() closed too early, breaks sg rule creation in cluster sg if custom source sg is defined.

outputs.tf
replace function doesn't accept null as replacement value
cause an issue when you try to use `module.eks.oidc_provider` it always be null
```shell
$ tf console
Acquiring state lock. This may take a few moments...
> replace("https://test.com.ar", "https://", null)
│
│ Error: Invalid function argument
│
│   on <console-input> line 1:
│   (source code not available)
│
│ Invalid value for "replace" parameter: argument must not be null.
╵
> try(replace("https://test.com.ar", "https://", null), null)
null
> try(replace("https://test.com.ar", "https://", ""), null)
"test.com.ar"
```
=> fix: Invalid value for "replace" parameter: argument must not be null.

README.md, examples/complete/README.md, examples/complete/versions.tf, examples/eks_managed_node_group/README.md, examples/eks_managed_node_group/main.tf, examples/eks_managed_node_group/versions.tf, examples/fargate_profile/README.md, examples/fargate_profile/main.tf, examples/fargate_profile/versions.tf, examples/karpenter/README.md, examples/karpenter/main.tf, examples/karpenter/versions.tf, examples/outposts/README.md, examples/outposts/versions.tf, examples/self_managed_node_group/README.md, examples/self_managed_node_group/versions.tf, main.tf, modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/versions.tf, modules/fargate-profile/README.md, modules/fargate-profile/versions.tf, modules/karpenter/README.md, modules/karpenter/versions.tf, modules/self-managed-node-group/README.md, modules/self-managed-node-group/versions.tf, versions.tf
- Add support for addon `configuration_values`
- Clean up examples to remove previous hacks for CoreDNS on EKS Fargate using new configuration argument
- This is now supported by the EKS API https://github.com/hashicorp/terraform-provider-aws/pull/28295
- Resolves #2344 
- No
=> feat: Add support for addon `configuration_values`

README.md, main.tf
- Use IAM session context data source to resolve the identities role when using `assumed_role`
- Ref: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2327#issuecomment-1355581682
- Ref: https://github.com/hashicorp/terraform-provider-aws/issues/28381
- No, this is backwards compatible
=> fix: Use IAM session context data source to resolve the identities role when using `assumed_role`

examples/eks_managed_node_group/main.tf
All environment variables have to be strings
Fixes the VPC CNI examples due to invalid data types.
The previous version resulted in the following error:
```
│ Error: error creating EKS Add-On (xxxx-cni): InvalidParameterException: ConfigurationValue provided in request is not supported [$.env.ENABLE_PREFIX_DELEGATION: boolean found, string expected, $.env.WARM_PREFIX_TARGET: integer found, string expected]
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "xxxxx-7139-4755-9bee-xxxxx"
│   },
│   AddonName: "vpc-cni",
│   ClusterName: "xxxx",
│   Message_: "ConfigurationValue provided in request is not supported [$.env.ENABLE_PREFIX_DELEGATION: boolean found, string expected, $.env.WARM_PREFIX_TARGET: integer found, string expected]"
│ }
```
- Resolves #2348
Also: Thanks for …
=> chore: Fix typo for vpc-cni addon example

node_groups.tf
- Add additional port for `metrics-server` to recommended rules
- `metrics-server` is a common utility in EKS clusters
- No
=> feat: Add additional port for `metrics-server` to recommended rules

node_groups.tf
- Correct map name for security group rule 4443/tcp
- Copy+paste error - https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2353#discussion_r1051644557
- No
=> fix: Correct map name for security group rule 4443/tcp

examples/fargate_profile/main.tf, examples/karpenter/main.tf, examples/outposts/main.tf
- Update examples to show Fargate profiles configured for high availability
- Fargate profiles are not automatically distributed across AZs; its recommended to create multiple profiles across multiple AZs for a highly available setup
=> chore: Update examples for Fargate high availability

main.tf
As per #2379, we manage the contents of the `aws-auth` ConfigMap with GitOps and ArgoCD.
The only issue we have is that ArgoCD automatically adds a label to every resource it updates and because `lifecycle_ignore` is only set on `data` we always have `terraform` wanting to remove the `metadata.label` added by ArgoCD (even though we have `manage_aws_auth_configmap=false` set, which semantically implies that this won't happen).
Fixes: #2379
This causes has no breaking changes.
=> feat: Ignore changes to labels and annotations on on `aws-auth` ConfigMap

modules/eks-managed-node-group/README.md, modules/self-managed-node-group/README.md
The vpc_id variable is not actually defined in this module as an input variable. 
This example in the readme can cause confusion if used since it does not work.
None
As a documentation update, I am not sure how this could be tested. I encountered it through a copy and paste issue of the example (vs. the module directly). I would appreciate any assistance testing this as needed as I do not intend to test it further, but wanted to update this for others.
=> docs: Removed `vpc_id` from nodegroup sub-module docs; removed in v19.x

node_groups.tf
I wonder if [kubernetes-sigs/prometheus-adapter](https://github.com/kubernetes-sigs/prometheus-adapter) can be added to the default recommended security groups.
When deployed with kube-prometheus/kube-prometheus-stack/helm/manifests it uses port 6443.
Thinking if metrics-server could be added by default so can prometheus-adapter.
To have the Kubernetes aggregated API [v1beta1.metrics.k8s.io/default](http://v1beta1.metrics.k8s.io/default) available by default if using the prom-adapter.
None
- [] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [] I have tested and validated these changes using one or more of the provided `examples/*` projects
=> feat: Add prometheus-adapter port 6443 to recommended sec groups

modules/eks-managed-node-group/README.md
The variable cluster_security_group_id was removed from the module, but the README still included it.
Documentation update to fix an example.
The example in the documentation contained a variable that was removed.
No breaking changes.
Tested this locally when trying to use the module.
=> docs: Update README to include changes to variables

modules/karpenter/README.md, modules/karpenter/main.tf, modules/karpenter/variables.tf
Added variable to control the prefix used for event bridge rules.
We are trying to use ABAC to control permissions of our CI/CD, using `ResourceTag` IAM condition wherever possible. It seems that EventBridge IAM permissions does not allow that so I would like to limit permissions by resource ARN, and for that I would like to control the prefix used for all rules - so I could give our CI/CD tool permissions to control only rules matching this prefix.
(Still testing, opened for feedback because it's my first PR)
=> feat: Allow to pass prefix for rule names

docs/compute_resources.md, docs/faq.md, docs/user_data.md, examples/eks_managed_node_group/README.md, examples/eks_managed_node_group/main.tf, examples/self_managed_node_group/README.md, examples/self_managed_node_group/main.tf, examples/user_data/main.tf
- Update documentation to remove previous method for specifying `containerd` runtime; this is now the default in Kubernetes `v1.24` and should not be specified anymore per the AWS docs 
- Update examples to ensure they are functioning as intended. 
- It looks like some recent additions to the VPC module for IPv6 have introduced some issues here that are now corrected. 
- I'm not sure why the KMS `key_id` stopped working and started throwing an error, but is working as intended again with `key_arn`
- It also looks like the KMS policy used for encrypting the EC2 volumes stopped functioning and caused instances to not launch properly. This has been updated to use the new policy specific to Autoscaling service linked roles and is working again
- With support for addon configuration, most of …
=> docs: Update documentation for 1.24 changes to containerd, ensure examples are functioning as intended

modules/karpenter/main.tf
Adds the necessary policy for https://github.com/aws/karpenter/pull/3363
=> feat: Add auto discovery permission of cluster endpoint to Karpenter role

docs/UPGRADE-19.0.md
Hi, 
thanks for your work ! 
Here a fix for a bullet list incorrectly indented in order to be displayed as a sub-element of `Removed variables:`
The migration guide was not rendered properly
-
-
=> docs: Correct indentation for the bullet list on upgrade guide

modules/karpenter/README.md, modules/karpenter/main.tf, modules/karpenter/variables.tf
allow setting custom IRSA policy name separately from custom role name.
You can use `irsa_name` currently to set them both to the same thing, but there is no way to give them each custom names.
Closes #2465 
My organization has requirements around role and policy names. The module only lets you set a role name currently, and uses that as the policy name. I need to be able to set a policy name, and a role name, and not to the same thing.
No. Made it backwards compatible.
I ran it locally on a project with all combinations of providing names or not.
=> feat: Allow setting custom IRSA policy name for karpenter

docs/UPGRADE-19.0.md
The new variable `node_security_group_enable_recommended_rules` is set to true by default and might cause incompatibilities with previous, additional rules.
While upgrading from version 18 to 19 I experienced issues with some custom `node_security_group_additional_rules` because I missed to remove all duplicates that are now part of `node_security_group_enable_recommended_rules`.
I think this should be listed in the incompatible changes, as it breaks the apply run if you miss to remove the duplicate rules.
The error you might receive will look like the following:
```
Error: [WARN] A duplicate Security Group rule was found on (sg-xxx). This may be a side effect of a now-fixed Terraform issue causing two security groups with identical attributes but different source_security_group_ids to …
```
=> docs: Add info about new variable to incompatible changes

docs/README.md
Add an entry to the documentation Table of content to reference the upgrade to v19.x guide.
The README of the documentation lists links to the different Markdown files in the doc directory, but the recent [UPGRADE-19.0.md](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/UPGRADE-19.0.md) is not listed.
No breaking changes
Only documentation. The rendering on the pull request is enough
=> docs: Update Documentation README ToC

main.tf
Add additional `Name` tag to the cloudwatch log group resource.
In addition to the name of the log group itself, we wanted to add the log group name _tag_ as well for our own cost reporting.
Ran this change locally against my existing EKS cluster. Here's an example of the plan below:
```
~ resource "aws_cloudwatch_log_group" "this" {
id                = "/aws/eks/awesome_cluster/cluster"
name              = "/aws/eks/awesome_cluster/cluster"
~ tags              = {
+ "Name" = "/aws/eks/awesome_cluster/cluster"
}
~ tags_all          = {
+ "Name"             = "/aws/eks/awesome_cluster/cluster"
}
}
```
=> fix: Add Name tag for EKS cloudwatch log group

examples/eks_managed_node_group/main.tf, modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/main.tf, modules/eks-managed-node-group/outputs.tf, modules/eks-managed-node-group/variables.tf, modules/self-managed-node-group/main.tf, modules/self-managed-node-group/outputs.tf, node_groups.tf
Allow settings autoscaling schedule for `eks_managed_node_group` module
We can set autoscaling schedules for `self_managed_node_group`, but we didn't have autoscaling schedules config for `eks_managed_node_group`.
I added 2 variables `create_schedule`, `schedules` and resource `aws_autoscaling_schedule` for `eks-managed-node-group` module
No
I deployed example: `eks_managed_node_group` on AWS and autoscaling schedule has been added
=> feat: Add Autoscaling schedule for EKS managed node group

modules/self-managed-node-group/README.md, modules/self-managed-node-group/main.tf, modules/self-managed-node-group/versions.tf
Add support for the `allowed_instance_types` parameter in the `instance_requirements` block of the self managed nodegroups ASG. 
This allowed additional flexibility when configuring the ASGs to use specific instance types. By defining the list of allowed instance types, we allow a more deterministic way of configuring our environment. Support for `allowed_instance_types` was added in `v4.57.0` of the aws provider, so have bumped up the version: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.57.0 
No expected breaking changes
=> feat: Add support for allowed_instance_type

examples/karpenter/main.tf
minor fix while reading through the comment
=> docs: Minor fix in comment

modules/karpenter/main.tf
`sqs_managed_sse_enabled` and `kms_master_key_id` cannot coexist. prior to this fix, if `queue_managed_sse_enabled` was set to `false`, then `sqs_managed_sse_enabled` would be set to false as well, instead `null`, as it should be in this case.
I have tried to change an SQS queue's encryption from "SSE-SQS" to "SSE-KMS", using the karpenter submodule and failed with an error saying **"sqs_managed_sse_enabled": conflicts with "kms_master_key_id"**.
This fixes the issue.
None known.
I have successfully deployed with this change in my environment, where SQS queues are managed by the karpenter submodule for about 2 months now.
I have executed `pre-commit run -a` on my pull request
=> fix: SQS queue encryption types selection

main.tf, modules/eks-managed-node-group/main.tf, modules/karpenter/main.tf
Ignore changes to `role_last_used` for `aws_iam_role.this[0]`, `module.eks_managed_node_group[*].aws_iam_role.this[0]`, and `module.eks_managed_node_group[*].aws_iam_role.irsa[0]`.
Without this commit, there is useless noise in drift detection in Terraform Enterprise, for example.
I shouldn't think so.
=> feat: Ignore changes to *.aws_iam_role.*.role_last_used

main.tf, modules/eks-managed-node-group/main.tf, modules/karpenter/main.tf
- Revert changes to ignore `role_last_used` in #2628
- The changes in #2628 are not working as intended, therefore this needs to be resolve by the provider https://github.com/hashicorp/terraform-provider-aws/issues/30861#issuecomment-1561757274
- The changes in #2628 are reliant on an attribute that was introduced in v4.64.0 of the AWS provider. We should have bumped the provider min supported version for this, but as is it is currently throwing an error for users that are not at v4.64.0+ 
- No
=> fix: Revert changes to ignore `role_last_used`

examples/karpenter/main.tf
=> docs: Correct comment mis-spelling

modules/karpenter/main.tf
This commit [2648](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2648)
With current permissions we are unable to use SnapshotID with Karpenter provisioner
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2648
No
Manually, by using local module with fixed permissions
=> fix: Snapshot permissions issue for Karpenter submodule

main.tf
First of all, thanks for the work on this module. We've been using it for a couple of years now ❤️ 
Use `coalesce` when the desired default value of an expression is not `null`.
We maintain an opinionated wrapper module around this one where we used to install the EKS add-ons using their separate Terraform resources but eventually switched to doing it through this module since it supports it.
On our module, we would like to support providing add-on versions while still keeping the default behavior from this module of retrieving the matching version from a data_source if no version is provided.
This would be a snippet from our module.
```
variable "coredns_version" {
type    = string
default = null
}
variable "kube_proxy_version" {
type    = string
default = null
}
```
```
... …
```
=> fix: Use `coalesce` when desired default value is not `null`

docs/faq.md, outputs.tf
This is a documentation update as a result of:
- https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1692
- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2687
The FAQ notes setting a new value for the `kubernetes.io/cluster/<CLUSTER_NAME>` tags in AWS should fix the problem, but its the _existence_ of the tag itself that confuses things like the AWS Load Balancer Controller. Removing this from the FAQ to avoid confusion.
N/A
I validated this as a part of https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1692
=> chore: Update FAQ for security group tagging

main.tf, modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/outputs.tf
This change adds additional checks for `platform == "windows"` on both `local.node_iam_role_arns_non_windows` and `local.node_iam_role_arns_windows`.
The additional validation in `local.node_iam_role_arns_windows` ensures that the correct configurations are added to `aws-auth`.
The additiional validation in `local.node_iam_role_arns_non_windows` ensures that terraform does not also create an extra incorrect entry in `aws-auth` for the node group.
To support this change, the eks_managed_node_group module has a new output (`platform`)
Resolves the issue described in this [comment](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2350#issuecomment-1428624704) from #2350 
No breaking changes found during my testing.
- [] I have updated at least one of the `examples/*` to …
=> feat: Add `node_iam_role_arns` local variable to check for Windows platform on EKS managed nodegroups

examples/eks_managed_node_group/main.tf
The sample usage of autoscaling group scheduled actions has a typo on time_zone definition
When using the sample, the time_zone parameter is not set accordingly on AWS.
Not applicable
=> docs: Correct `time_zone` argument on example autoscaling group schedule

.pre-commit-config.yaml, README.md, examples/complete/README.md, examples/complete/versions.tf, examples/eks_managed_node_group/README.md, examples/eks_managed_node_group/versions.tf, examples/fargate_profile/README.md, examples/fargate_profile/versions.tf, examples/karpenter/README.md, examples/karpenter/versions.tf, examples/outposts/README.md, examples/outposts/prerequisites/versions.tf, examples/outposts/versions.tf, examples/self_managed_node_group/README.md, examples/self_managed_node_group/main.tf, examples/self_managed_node_group/versions.tf, modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/versions.tf, modules/fargate-profile/README.md, modules/fargate-profile/versions.tf, modules/karpenter/README.md, modules/karpenter/versions.tf, modules/self-managed-node-group/main.tf, versions.tf
As started in https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2552, this PR will add the `allowed_instance_types` option but on the self-managed ASG this time.
This option could be configured on the Launch Template or the ASG itself but it's easier to see it in AWS Console when it's managed at the ASG level and not buried on the LT (when the situation permits it). It also follow the existing module convention to work with instance attributes scaling.
None
=> feat: Add support for `allowed_instance_types` on self-managed nodegroup ASG

main.tf
This change modifies the OIDC provider `thumbprint_list`, so that it only contains the CA fingerprint, rather than all fingerprints.
Addresses #2732, by reverting the change from #2307.
According to the description of #2732, #2307 introduced the inclusion of all certificate fingerprints in the `thumbprint_list`. Based on a later documentation change in hashicorp/terraform-provider-aws#32847, only the CA fingerprint should be included in the `thumbprint_list`.
From the [latest docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#enabling-iam-roles-for-service-accounts), the following should be used:
> thumbprint_list = [data.tls_certificate.example.certificates[0].sha1_fingerprint]
This shouldn't break existing functionality, since the root CA …
=> fix: Only include CA thumbprint in OIDC provider list

.pre-commit-config.yaml, examples/karpenter/main.tf, modules/karpenter/README.md, modules/karpenter/main.tf, modules/karpenter/variables.tf
- Karpenter node IAM role policies variable should be a map of strings, not list
- Update Karpenter example to show attaching policies on the node IAM role which is more common that attaching additional  policies on the IRSA role
- Resolves #2750
- No
=> fix: Karpenter node IAM role policies variable should be a map of strings, not list

modules/eks-managed-node-group/main.tf, modules/self-managed-node-group/main.tf
Following issue #2753.
Currently, it is not possible to provide a license through the `self-managed-node-group` and `eks-managed-node-group` modules. 
This is necessary in cases like the following configuration:
```tf
placement = {
tenancy                 = "host"
host_resource_group_arn = ......
}
```
- Resolves #2753
I do not see any potential breaking changes.
After these modifications, I can define `license_configuration_arn` as follows:
```tf
module "self_managed_node_group" {
source  = "terraform-aws-modules/eks/aws//modules/self-managed-node-group"
version = "19.17.2"
name                = local.eks_name
cluster_name        = module.eks.cluster_name
cluster_version     = var.eks_version
cluster_endpoint    = module.eks.cluster_endpoint
cluster_auth_base64 = …
```
=> fix: Correct key used on `license_configuration_arn` 

examples/complete/main.tf
Following issue https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2699, adding a sample in complete example in order to show how to add an EBS disk correctly
Adding a disk doesn't seem to be explicite. Moreover, it doesn't appear in complete exemple
None
=> docs: Add ebs disk in complete example

.pre-commit-config.yaml, CHANGELOG.md, examples/karpenter/README.md, examples/karpenter/main.tf, modules/karpenter/README.md, modules/karpenter/main.tf, modules/karpenter/variables.tf
Add IAM support for Karpenter v1beta1 resources.
The recent Karpenter v0.32 release added support for v1beta1 resources, as described in https://github.com/aws/karpenter/blob/main/designs/v1beta1-full-changelist.md. As part of this change, new permissions are needed such as the ability to create instance profiles.
The new controller IAM policy is described in https://github.com/aws/karpenter/blob/main/website/content/en/preview/upgrading/v1beta1-controller-policy.json
This PR adds a minimal set of changes for v0.32 compatibility, specifically around instance profiles. This gives the IRSA role the ability to create any instance profile in the account, without attempting to scope it down based on tags as https://github.com/aws/karpenter/pull/3948 would have done.
No breaking changes, only …
=> feat: Add Karpenter v1beta1 compatibility

README.md, main.tf, modules/karpenter/main.tf
- Update KMS module to avoid calling data sources when `create_kms_key = false`
- Diff is safe for upgrade https://github.com/terraform-aws-modules/terraform-aws-kms/compare/v1.1.0...v2.1.0
- Correct logic used by Karpenter module for CNI IPv6 policy ARN
- Resolves #2794
- Relates to #2803 
- No
=> feat: Update KMS module to avoid calling data sources when `create_kms_key = false`

modules/karpenter/main.tf
- Remove additional conditional on Karpenter instance profile creation to support upgrading
- When upgrading to 0.32, Karpenter will now create the instance profile used by the nodes that it creates. The permissions to support this were added in #2800. However, removing the instance profile too soon can cause disruptions since existing nodes will still be using this profile until Karpenter replaces all of those existing nodes with new nodes that are using an instance profile that *IT has created. Since there is already a conditional on the profile creation (`create_instance_profile`), we are removing the additional conditional added in #2800 to allow users to opt into the new permissions required for 0.32, and then later opt out of the module created instance profile once they feel its …
=> fix: Remove additional conditional on Karpenter instance profile creation to support upgrading

README.md, examples/eks_managed_node_group/README.md, examples/eks_managed_node_group/main.tf, main.tf
- Correct cluster access entry to create one entry and multiple policy associations. Currently, it is trying to use the flattened logic that was intended for supporting multiple policy associations
- Want: Per access entry, support multiple policy associations
- Current: One access entry per policy association, and if multiple policies are provided, it will fail since entry already exists
- Provide code to validate the functionality as well as document the schema for users
- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2881#issuecomment-1924502935
- Technically, yes - the looping logic of the access entry has changed. However, this is not working as it was intended and we are coming off a breaking change so I am inclined to add this as a bugfix since it was never …
=> fix: Correct cluster access entry to create multiple policy associations per access entry

README.md, outputs.tf
Adds to `outputs.tf`
```hcl
output "access_policy_associations" {
description = "Map of eks cluster access policy associations created and their attributes"
value       = aws_eks_access_policy_association.this
}
```
fixes #2903 
n/a
Ran this locally for the issue I mentioned in #2903 and was able to fix my dependency issue with explicit `depends_on` referencing `module.aws_eks.access_entries` and `module.aws_eks.access_policy_associations`.
=> feat: Add output for `access_policy_associations`

main.tf
Change the default kubernetes group from [] to null - it's possible that EKS will manage this attribute by adding in groups like system:nodes when specifying a type of EC2_LINUX or similar. This attribute should be unspecified if STANDARD is not defined. 
Resolves the module attempting to change EC2_LINUX from removing the kubernetes groups set by EKS and EC2_LINUX types. 
- Resolves #2896
No
Tested on eks_managed_node_group by modifying the access_entities to use a EC2_LINUX type.
=> fix: Update access entries `kubernetes_groups` default value to `null`

modules/karpenter/README.md, modules/karpenter/main.tf, modules/karpenter/variables.tf
Made a new variable in the karpenter submodule "enable_pod_identity" which allows pod identities to be disabled.
Pod identities are not currently available in all partitions, and this principal being present in these locations causes the module to fail.
- Resolves #2901 
No, the default is set to true which has the same behavior as before
=> feat: Allow enable/disable of EKS pod identity for the Karpenter controller

modules/karpenter/main.tf
This change adds a condition on the statement with id `AllowInterruptionQueueActions` that checks `enable_spot_termination` value, since, if the variable is false, the `aws_sqs_queue` resource will not be created.
Resolves: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2906
No breaking changes.
=> fix: Karpenter `enable_spot_termination = false` should not result in an error

examples/fargate_profile/main.tf
Change the custom annotation on coredns pods to `fargate` instead of `Fargate`.
I just set up a cluster using Fargate for the `kube-system` namespace, and the additional configuration for coredns as expressed by the example subject of this PR failed, because the node taint is against an annotation with value `fargate`.
=> docs: Lowercase Fargate compute type annotation value

docs/UPGRADE-20.0.md, examples/karpenter/main.tf
- Update Karpenter example versions
- Add additional clarification on access entry migration to upgrade guide
- At the time of v20 release, Karpenter did not support EKS 1.29 but now it does with v0.34.0 - all examples now use 1.29
- Ref https://github.com/terraform-aws-modules/terraform-aws-eks/issues/2912#issuecomment-1936876065
- No
=> docs: Update Karpenter example version; add additional clarification on access entry migration to upgrade guide

.pre-commit-config.yaml, modules/karpenter/main.tf
- Replace Karpenter SQS policy dynamic service princpal DNS suffixes with static `amazonaws.com`
- Resolves #2932 
- No
=> fix: Replace Karpenter SQS policy dynamic service princpal DNS suffixes with static `amazonaws.com`

examples/eks_managed_node_group/main.tf, modules/eks-managed-node-group/main.tf
- Use the `launch_template_tags` on the launch template
- Ensure the variable is used as it was intended - on the launch template
- No
=> fix: Use the `launch_template_tags` on the launch template

modules/eks-managed-node-group/main.tf, modules/eks-managed-node-group/migrations.tf, modules/karpenter/main.tf, modules/karpenter/migrations.tf, modules/self-managed-node-group/main.tf, modules/self-managed-node-group/migrations.tf
- Use static keys for IAM role policy attachment
The use of `toset()` in `for_each` loops is known to be problematic. In hindsight, this should have been corrected during v20.0 but it must have been an oversight on my part. The use of `toset()` on the static policy attachment (custom/additional policy attachment was added awhile back with static keys) has worked without issue except for scenarios where users try to use an explicit `depends_on` (which is [not recommended](https://github.com/hashicorp/terraform/issues/30340#issuecomment-1010202582) across modules for a number of reasons). 
Why is this an issue now? We have an issue with our user data where the cluster service CIDR is not being passed properly, causing nodes to have the wrong internal IP. Oddly enough, we haven't seen user …
=> feat: Replace the use of `toset()` with static keys for node IAM role policy attachment

modules/karpenter/main.tf
Karpenter module fails
```
│ Error: Invalid index
│ 
│   on .terraform/modules/eks.eks_karpenter/modules/karpenter/main.tf line 576, in resource "aws_iam_role_policy_attachment" "node":
│  576:   role       = aws_iam_role.node[0].name
│     ├────────────────
│     │ aws_iam_role.node is empty tuple
│ 
│ The given key does not identify an element in this collection value: the
│ collection has no elements.
╵
```
if node role is not created:
```
module "eks_karpenter" {
source  = "terraform-aws-modules/eks/aws//modules/karpenter"
version = "~> 20.0"
cluster_name = module.eks.cluster_name
create_iam_role          = true
create_node_iam_role          = false
}
```
Bugfix
No, it's a minor fix
=> fix: Do not attach policy if Karpenter node role is not created by module

examples/karpenter/README.md, examples/outposts/README.md, outputs.tf
This changeset adds `depends_on` to a few cluster outputs. This will tell terraform that these cluster outputs should not be made "known" and available until all the EKS access entries have completed. The outputs selected in this PR are limited to those used for authenticating to the EKS cluster. If it turns out more are needed, it is easy enough to add them, and I am not aware of any further repercussions to this particular usage of `depends_on`.
- Resolves #2923
Without this change, it can be difficult to order the terraform lifecycle on create and destroy when also using the helm, kubectl, and/or kubernetes providers. It requires using `state rm` and `-target` to get things to complete successfully. With this change, you can just apply and destroy normally. See also the comment and …
=> fix: Forces cluster outputs to wait until access entries are complete

.pre-commit-config.yaml, docs/compute_resources.md, docs/user_data.md, examples/eks_managed_node_group/README.md, examples/eks_managed_node_group/main.tf, examples/eks_managed_node_group/outputs.tf, examples/fargate_profile/README.md, examples/fargate_profile/outputs.tf, examples/karpenter/README.md, examples/karpenter/outputs.tf, examples/outposts/README.md, examples/outposts/outputs.tf, examples/self_managed_node_group/README.md, examples/self_managed_node_group/main.tf, examples/self_managed_node_group/outputs.tf, examples/user_data/main.tf, modules/_user_data/README.md, modules/_user_data/main.tf, modules/_user_data/outputs.tf, modules/_user_data/variables.tf, modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/main.tf, modules/eks-managed-node-group/outputs.tf, modules/eks-managed-node-group/variables.tf, modules/self-managed-node-group/README.md, modules/self-managed-node-group/main.tf, modules/self-managed-node-group/outputs.tf, modules/self-managed-node-group/variables.tf, node_groups.tf, outputs.tf
- Propagate the `ami_type` down to the self-managed nodegroup. This allows users to specify just the `ami_type` instead of needing to specify the `ami_type` and the `platform` (which is redundantly annoying). The `platform` functionality is still preserved for backwards compatibility until its removed in the next major version release
- Fix the `cluster_service_cidr` output; previously it would output either the IPv4 CIDR or `null`, which is incorrect for IPv6 clusters
- This simplifies and unifies the user experience across both EKS managed node groups and self-managed node groups, it also allow users to opt into the v21 functionality now instead of waiting which will future proof their configurations
- No; validated by deploying EKS managed node group and self-managed node group …
=> feat: Propagate `ami_type` to self-managed node group; allow using `ami_type` only

modules/fargate-profile/README.md, modules/fargate-profile/main.tf
[As suggested in AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/pod-execution-role.html#check-pod-execution-role) to prevent the security issue known as the [confused deputy problem](https://docs.aws.amazon.com/IAM/latest/UserGuide/confused-deputy.html), adds `SourceArn` condition to `fargate-profile` module's `assume_role_policy`
Fixes #3038.
[Suggested IAM trust policy per AWS docs](https://docs.aws.amazon.com/eks/latest/userguide/pod-execution-role.html#check-pod-execution-role) "to avoid a [confused deputy security problem](https://docs.aws.amazon.com/IAM/latest/UserGuide/confused-deputy.html)."
Potentially breaks workflows where users may be using/assuming the IAM role generated by `fargate-profile` in an unintended manner, namely from other EKS instances.
=> feat: Add `SourceArn` condition to Fargate profile trust policy

main.tf
Ignore changes to bootstrap_cluster_creator_admin_permissions to allow upgrading module and importing existing clusters
Fixes: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/3025
None
=> fix: Ignore changes to `bootstrap_cluster_creator_admin_permissions` which is disabled by default 

docs/faq.md, main.tf
Includes a reference to AWS documentation for EKS Cluster addon names and configuration details. 
I'm happy to write a more in-depth description with examples but I wasn't sure of the best place to do so, so I went with the simplest solution. Feel free to let me know if there's a more reasonable place for this to live. 
Assists operators in more easily discerning the precise addon names to include in their modules. 
Closes #3008 
No
=> docs: Include ref to addon naming and config documentation 

docs/UPGRADE-19.0.md, main.tf
- Starting with `1.30`, do not use the cluster OIDC issuer URL by default in the identity provider config
- The example referenced in the v19 upgrade doc has been corrected to better reflect the intended behavior enforced by this change
- Starting in Kubernetes 1.30, there are improved restrictions on authentication. From https://github.com/kubernetes/kubernetes/pull/123561:
> Conflicting issuers between JWT authenticators and service account config are now detected and fail on API server startup.  Previously such a config would run but would be inconsistently effective depending on the credential.
The prior default value of the cluster (control plane) OIDC issuer URL was incorrect and should not be used in this context. Users should provider their issuer's URL for their identity provider …
=> feat: Starting with `1.30`, do not use the cluster OIDC issuer URL by default in the identity provider config

main.tf
- Correct syntax for correctly ignoring `bootstrap_cluster_creator_admin_permissions` and not all of `access_config`
- Resolves #3052
- No
=> fix: Correct syntax for correctly ignoring `bootstrap_cluster_creator_admin_permissions` and not all of `access_config`

.pre-commit-config.yaml, modules/self-managed-node-group/README.md, modules/self-managed-node-group/main.tf, modules/self-managed-node-group/variables.tf, node_groups.tf
- Require users to supply OS via `ami_type` and not via `platform` which is unable to distinquish between the different variants
- Resolves #3062
- No
=> feat: Require users to supply OS via `ami_type` and not via `platform` which is unable to distinquish between the number of variants supported today

modules/karpenter/main.tf
I would like to deny access to AWS SQS through HTTP by AWS SQS access policy due to security reasons.
[SQS security best practices](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-security-best-practices.html)
https://github.com/aws/karpenter-provider-aws/pull/6395
No
=> feat: Deny HTTP on Karpenter SQS policy

.pre-commit-config.yaml, modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/main.tf, modules/eks-managed-node-group/variables.tf, modules/fargate-profile/README.md, modules/fargate-profile/main.tf, modules/fargate-profile/variables.tf, modules/karpenter/README.md, modules/karpenter/main.tf, modules/karpenter/variables.tf, modules/self-managed-node-group/README.md, modules/self-managed-node-group/main.tf, modules/self-managed-node-group/variables.tf, node_groups.tf, tests/eks-managed-node-group/main.tf
- Add support for custom IAM role policy (inline role policy)
- Allows flexibility to add custom permissions as needed
- No
=> feat: Add support for custom IAM role policy

README.md, examples/eks-managed-node-group/versions.tf, examples/karpenter/README.md, examples/karpenter/versions.tf, examples/outposts/README.md, examples/outposts/prerequisites/versions.tf, examples/outposts/versions.tf, examples/self-managed-node-group/versions.tf, modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/main.tf, modules/eks-managed-node-group/versions.tf, modules/fargate-profile/README.md, modules/fargate-profile/versions.tf, modules/karpenter/README.md, modules/karpenter/versions.tf, modules/self-managed-node-group/README.md, modules/self-managed-node-group/versions.tf, tests/eks-managed-node-group/README.md, tests/eks-managed-node-group/versions.tf, tests/fargate-profile/README.md, tests/fargate-profile/versions.tf, tests/self-managed-node-group/README.md, tests/self-managed-node-group/versions.tf, versions.tf
- Add support for ML capacity block reservations with EKS managed node group(s)
- New `capacity_type` value of `CAPACITY_BLOCK` was added in https://github.com/hashicorp/terraform-provider-aws/pull/38216 
- Add support for using ML capacity block reservations with EKS managed node group(s)
- No
- Tested internally
=> feat: Add support for ML capacity block reservations with EKS managed node group(s)

main.tf
- Revert #3058 - fix: Invoke aws_iam_session_context data source only when required
https://github.com/terraform-aws-modules/terraform-aws-eks/pull/3058#issuecomment-2211247209
=> fix: Revert #3058 - fix: Invoke aws_iam_session_context data source only when required

.pre-commit-config.yaml, README.md, examples/eks-managed-node-group/versions.tf, examples/karpenter/README.md, examples/karpenter/versions.tf, examples/outposts/README.md, examples/outposts/prerequisites/versions.tf, examples/outposts/versions.tf, examples/self-managed-node-group/versions.tf, main.tf, modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/versions.tf, modules/fargate-profile/README.md, modules/fargate-profile/versions.tf, modules/karpenter/README.md, modules/karpenter/versions.tf, modules/self-managed-node-group/README.md, modules/self-managed-node-group/versions.tf, tests/eks-managed-node-group/README.md, tests/eks-managed-node-group/main.tf, tests/eks-managed-node-group/versions.tf, tests/fargate-profile/README.md, tests/fargate-profile/versions.tf, tests/self-managed-node-group/README.md, tests/self-managed-node-group/versions.tf, variables.tf, versions.tf
- Add support for `upgrade_policy`
- Resolves #3110 
- No
=> feat: Add support for `upgrade_policy`

main.tf
See linked issue #3118
Fixes #3118
Related #2760 
Related #2681 
Related #2337
None
=> fix: Eliminates null check on tag values to fix for_each error about unknown *keys*

README.md, examples/karpenter/README.md, examples/karpenter/outputs.tf, examples/outposts/README.md, examples/outposts/outputs.tf, outputs.tf, tests/eks-managed-node-group/README.md, tests/eks-managed-node-group/outputs.tf, tests/fargate-profile/README.md, tests/fargate-profile/outputs.tf, tests/self-managed-node-group/README.md, tests/self-managed-node-group/outputs.tf
- Add new output values for OIDC issuer URL and provider that are dual-stack compatible
- Resolves #2992
- Related to recent feature launch to support dual-stack compatibility https://github.com/aws/containers-roadmap/issues/2038
Note: this can be used for both IPv4 and IPv6 clusters
=> feat: Add new output values for OIDC issuer URL and provider that are dual-stack compatible

.pre-commit-config.yaml, modules/karpenter/main.tf
- Correct Karpenter EC2 service principal DNS suffix in non-commercial regions
- Resolves #3155 
- No
=> fix: Correct Karpenter EC2 service principal DNS suffix in non-commercial regions

modules/self-managed-node-group/main.tf
The launch template config in self-managed-node-group didn't include the parameter to set `primary_ipv6`, so I add it here. This has already been implemented for eks-managed-node-group in [this PR ](https://github.com/terraform-aws-modules/terraform-aws-eks/pull/3098)
This parameter is needed to enable `Assign primary IPv6 IP` for self-managed-node-group nodes. This is required to make it possible to use instance-type targets when using IPv6 and AWS Load Balancer Controller
Simple addition, no breaking changes
=> fix: Add `primary_ipv6` parameter to self-managed-node-group

.pre-commit-config.yaml, docs/UPGRADE-20.0.md
- Correct reference module implementation names to be unique in v20 upgrade guide
- https://github.com/terraform-aws-modules/terraform-aws-eks/issues/3136#issuecomment-2398327975
- No
=> docs: Correct reference module implementation names to be unique in v20 upgrade guide

modules/karpenter/policy.tf
Fix Karpenter module iam policy passrole to ec2 api bug. Related issue: #3190 
The current iam:PassRole action condition only works for ec2.amazonaws.com, can't work for ec2.amazonaws.com.cn
If use karpenter module at AWS CN, it would throw the unauthorized error when Karpenter pods try to create new instances, the Karpenter iam role can't pass to Karpenter node iam role because of the ec2 api(ec2.amazonaws.com) is not correct.
- Resolves #3190
`
statement {
sid       = "AllowPassingInstanceRole"
resources = var.create_node_iam_role ? [aws_iam_role.node[0].arn] : [var.node_iam_role_arn]
actions   = ["iam:PassRole"]
condition {
test     = "StringEquals"
variable = "iam:PassedToService"
values   = ["ec2.amazonaws.com"]
}
}
`
No, it does not break backwards compatibility with the current …
=> fix: Use dynamic partition data source to determine DNS suffix for Karpenter EC2 pass role permission

README.md, examples/eks-managed-node-group/versions.tf, examples/karpenter/README.md, examples/karpenter/versions.tf, examples/self-managed-node-group/versions.tf, main.tf, modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/versions.tf, modules/fargate-profile/README.md, modules/fargate-profile/versions.tf, modules/karpenter/README.md, modules/karpenter/versions.tf, modules/self-managed-node-group/README.md, modules/self-managed-node-group/versions.tf, tests/eks-managed-node-group/README.md, tests/eks-managed-node-group/main.tf, tests/eks-managed-node-group/versions.tf, tests/fargate-profile/README.md, tests/fargate-profile/versions.tf, tests/self-managed-node-group/README.md, tests/self-managed-node-group/main.tf, tests/self-managed-node-group/versions.tf, versions.tf
- Add support for pod identity association on EKS addons
- Support pod identity associations on EKS addons
- https://github.com/hashicorp/terraform-provider-aws/pull/39973
- https://github.com/hashicorp/terraform-provider-aws/issues/38357
- No
=> feat: Add support for pod identity association on EKS addons

main.tf, node_groups.tf, tests/fast-addons/README.md, tests/fast-addons/main.tf, tests/fast-addons/outputs.tf, tests/fast-addons/versions.tf, variables.tf
- Replace instances of `aws_eks_cluster.this[0].name` with `aws_eks_cluster.this[0].id`. The resultant value is the same, the name of the EKS cluster, but the use of `id` is important with respect to dependency management. The `.name` attribute is simply a pass through of what users provide and will "return early" whereas the `.id` is unique within Terraform since it is the key of the specific resource within the Terraform state map, and therefore is only made available upon success resource creation. The use of `.id` ensures that any implicit dependencies are forced to wait until the value is made available. [Reference](https://github.com/hashicorp/terraform-provider-aws/blob/dff0abbc69cf12aa215b88805e16300f1f3f83ad/internal/service/eks/cluster.go#L438-L444)
- Change the default value …
=> feat: Improve addon dependency chain and decrease time to provision addons (due to retries)

modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/variables.tf
Turn off detailed monitoring of EKS managed node groups by default.
Detailed monitoring gets expensive, and users who are new to the module may not know this setting exists. If someone discovers they want this setting, they could turn it on.
None
=> chore: Add `TODO` to turn off detailed monitoring by default at next breaking change

examples/karpenter/main.tf, main.tf
- Create EKS Auto Mode role when Auto Mode is enabled, regardless of built-in node pool use
- Disable data sources entirely when `create = false`
- Resolves #3232 
- No
=> fix: Create EKS Auto Mode role when Auto Mode is enabled, regardless of built-in node pool use

main.tf
- Avoid trying to attach the node role when Auto Mode nodepools are not specified
- Resolves #3238
- No
=> fix: Avoid trying to attach the node role when Auto Mode nodepools are not specified

README.md, examples/eks-auto-mode/README.md, examples/eks-auto-mode/versions.tf, examples/eks-hybrid-nodes/README.md, examples/eks-hybrid-nodes/versions.tf, examples/eks-managed-node-group/versions.tf, examples/karpenter/README.md, examples/karpenter/versions.tf, examples/self-managed-node-group/versions.tf, modules/eks-managed-node-group/README.md, modules/eks-managed-node-group/versions.tf, modules/fargate-profile/README.md, modules/fargate-profile/versions.tf, modules/hybrid-node-role/README.md, modules/hybrid-node-role/versions.tf, modules/karpenter/README.md, modules/karpenter/versions.tf, modules/self-managed-node-group/README.md, modules/self-managed-node-group/versions.tf, tests/eks-fargate-profile/README.md, tests/eks-fargate-profile/versions.tf, tests/eks-hybrid-nodes/README.md, tests/eks-hybrid-nodes/versions.tf, tests/eks-managed-node-group/README.md, tests/eks-managed-node-group/versions.tf, tests/fast-addons/README.md, tests/fast-addons/versions.tf, tests/self-managed-node-group/README.md, tests/self-managed-node-group/versions.tf, versions.tf
- Update min provider version to remediate cluster replacement when enabling EKS Auto Mode
- https://github.com/hashicorp/terraform-provider-aws/pull/40415
- Resolves #3236
- No
=> fix: Update min provider version to remediate cluster replacement when enabling EKS Auto Mode

README.md, main.tf, variables.tf
- Auto Mode custom tag policy should apply to cluster role, not node role
- Currently this is incorrect per https://docs.aws.amazon.com/eks/latest/userguide/auto-learn-iam.html#tag-prop and therefore instances fail to provision when custom tags are applied to a node class
- Claiming this as a no since it never worked as intended. Yes, the policy will be destroyed and permissions removed from the node but those permissions were not being used for anything - they need to be applied to the cluster role
=> fix: Auto Mode custom tag policy should apply to cluster role, not node role

examples/karpenter/README.md, examples/karpenter/inflate.yaml, examples/karpenter/karpenter.yaml, examples/karpenter/main.tf, examples/karpenter/versions.tf
I suggest replacing the kubectl provider in examples due to security concerns, as the current provider's developer may be potentially based in russia.
- Resolves #3244
=> chore: Remove `kubectl` provider from Karpenter example

.pre-commit-config.yaml, docs/UPGRADE-20.0.md
- Update v20 upgrade guide to clarify that `"CONFIG_MAP"` is not a supported access type
- Resolves #3247
- No
=> docs: Update v20 upgrade guide to clarify that `"CONFIG_MAP"` is not a supported access type

main.tf
While Creating Access entry for Self managed node role, we were getting below error as it seems EC2 type is in exception for policy attachment. Once I removed EC2 from exception condition, it started picking up Policy attachment and Access Entry got created. We need this for creating Access Entry for Node role in EKS Automode.
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/eks/main.tf line 289, in resource "aws_eks_access_policy_association" "this":
│  289:   policy_arn    = each.value.association_policy_arn
│     ├────────────────
│     │ each.value is object with 3 attributes
│ 
│ This object does not have an attribute named "association_policy_arn".
I have removed EC2 from exception list of policy attachment. Once done, it start creating policy attachment for EC2 type …
=> fix: Allow `"EC2"` access entry type for EKS Auto Mode custom node pools

modules/karpenter/policy.tf
…pacity-reservation permission as part of Karpenter version 1.3.0
Karpenter version 1.3.0 now has a feature that allows for On Demand Capacity Reservation Support. The policy attached to the KarpenterController needs to be updated to allow this. More info can be found here: https://github.com/aws/karpenter-provider-aws/releases/tag/v1.3.0
As part of this update, the AllowScopedEC2InstanceAccessActions policy needs to be updated to allow for Capacity Reservations to be made through Karpenter. Karpenter have updated their docs for this see - https://github.com/aws/karpenter-provider-aws/pull/7801/files
No breaking changes
=> feat: Add capacity reservation permissions to Karpenter IAM policy

modules/eks-managed-node-group/main.tf
Currently when you don't set a value of `desired_capacity`, `min_size` or `max_size` it replaces them with `0` which end's up being an invalid parameter combination. 
**Config block**
```tf
"Scale Out" = {
desired_size = 7
min_size     = 7
...
}
```
**Payload result**
```
"requestParameters": {
"autoScalingGroupName": "xyz"
"scheduledActionName": "Scale Out",
"minSize": 7,
"maxSize": 0,
"desiredCapacity": 7,
},
```
The docs for the `aws_autoscaling_schedule` options [desired_capacity](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_schedule#desired_capacity-1), [max_size](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_schedule#max_size-1) and [min_size](https://registry.terraform.io/providers/hashicorp/aws/lat …
=> feat: Default to not changing autoscaling schedule values at the scheduled time

examples/eks-managed-node-group/eks-al2023.tf
Set AMI type explicitly   into user data type to be able to use cloudinit_pre_nodeadm 
https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/_user_data/main.tf#L33
If I dont set ami_type       = "AL2023_x86_64_STANDARD",
cloudinit_pre_nodeadm is not configured for user-data 
it is used https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/_user_data/main.tf#L19 and 
default ami_type is null in the examples
=> docs: Set ami_type for AL2023 in the example

node_groups.tf
Add missing `additional_cluster_dns_ips` variable definition and forwarding in the main module file `node_group.tf`.
The `additional_cluster_dns_ips` variable was not previously declared or passed in the main module (`node_group.tf`). This caused issues when attempting to use `self.additional_cluster_dns_ips` as an input to downstream modules such as `self-managed-node-group` and `_user_data`.
By explicitly defining and forwarding the variable, this fix enables proper DNS IP customization for NodeLocal DNS and similar use cases.
No breaking changes. This PR only adds support for an optional input variable.
=> fix: Ensure `additional_cluster_dns_ips` is passed through from root module

modules/_user_data/main.tf, modules/eks-managed-node-group/main.tf, modules/self-managed-node-group/main.tf
Add support for the AL2023 ARM64 NVIDIA variants
allow users to deploy this variant, based on the instructions in https://docs.aws.amazon.com/eks/latest/userguide/retrieve-ami-id.html
None
additions to enums, SSM paths are validated
```bash
> aws ssm get-parameter --name /aws/service/eks/optimized-ami/1.32/amazon-linux-2023/arm64/nvidia/recommended/image_id
{
"Parameter": {
"Name": "/aws/service/eks/optimized-ami/1.32/amazon-linux-2023/arm64/nvidia/recommended/image_id",
"Type": "String",
"Value": "ami-022ceb29ab1ee37d6",
"Version": 7,
"LastModifiedDate": "2025-05-22T00:35:45.511000+00:00",
"ARN": "arn:aws:ssm:us-west-2::parameter/aws/service/eks/optimized-ami/1.32/amazon-linux-2023/arm64/nvidia/recommended/image_id",
"DataType": "text"
}
}
> aws ssm get-parameter --name …
```
=> feat: Add AL2023 ARM64 NVIDIA variants

modules/karpenter/policy.tf
AWS CN requires both service principals in the IAM policy passrole condition. Added ec2.amazonaws.com as a default principal.
Fails to create EC2NodeClasses without this change in AWS CN
`{"level":"ERROR","time":"2025-07-17T09:48:10.169Z","logger":"controller","message":"Reconciler error","commit":"a2875e3","controller":"nodeclass.status","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","EC2NodeClass":{"name":"gpu"},"namespace":"","name":"gpu","reconcileID":"f6a8cdf5-e6c3-4329-bf32-fa1973febf1a","error":"creating instance profile, adding role \"staging-cn-nw-1-kpt-eks-node-group-20250716100915634200000001\" to instance profile \"staging-cn-nw-1-eks_14906149492098168839\", AccessDenied: User: arn:aws-cn:sts::XXX:assumed-role/KarpenterController-2025071613285168520000000 …
=> fix: Allow for both `amazonaws.com.cn` and `amazonaws.com` conditions in PassRole as required for AWS CN

modules/self-managed-node-group/main.tf, tests/self-managed-node-group/main.tf
- Allow `instance_requirements` to be set in self-managed node groups
- Correct self-managed node group test case for `instance_requirements`; this was incorrectly indented under another node group in the example for a few years now 😅 
- Resolves #3453
- Closes #3454
- No
=> fix: Allow `instance_requirements` to be set in self-managed node groups

modules/karpenter/policy.tf
Sync with Karpenter upstream IAM permissions
Missing IAM permissions
=> fix: Sync Karpenter IAM permissions with upstream
