- templates/config-map-aws-auth.yaml.tpl
- templates/kubeconfig.tpl
- templates/userdata.sh.tpl
Fix to add templates left out of the last PR
> forgot to add templates

- workers.tf
> #34 - asg size changes should be ignored - desired_capacity

- README.md
- cluster.tf
- local.tf
- templates/kubeconfig.tpl
- variables.tf
> Configurable workstation cidr

- local.tf
> fixed specifying cluster and worker security group

- CHANGELOG.md
> Updating changelog for v1.5.0 release

- CHANGELOG.md
- local.tf
- workers.tf
Fix for https://github.com/terraform-aws-modules/terraform-aws-eks/issues/116
> Fix for "" AMI ID error in PR 115

- CHANGELOG.md
…to remove workstation_external_ip from state (breaking change). 
As suggested here https://github.com/terraform-aws-modules/terraform-aws-eks/issues/114
> Note/instruction for people upgrading from 1.4 

- .travis.yml
- examples/eks_test_fixture/main.tf
- workers.tf
Getting travis to work since 0.11.8 was released. Example: https://travis-ci.org/terraform-aws-modules/terraform-aws-eks/builds/436638972
> Fixing travis config

- CHANGELOG.md
- local.tf
- workers.tf
> Add suspended_processes attributes to autoscaling_group

- CHANGELOG.md
> Updating changelog for v1.7.0

- CHANGELOG.md
- local.tf
- workers.tf
Add target group attribute support to workers ASG.
Fix #166
> Add target_group_arns to worker ASG

- .github/ISSUE_TEMPLATE.md
No code changes, just fixed a typo in the issue template. I don't think this needs to go in the changelog.
- [] I've added my change to CHANGELOG.md
> Fix a typo in the issue template

- CHANGELOG.md
> Updating changelog for v1.8.0

- README.md
Just making the example in the README a bit more complete with a worker group.
> Making README example more complete

- CHANGELOG.md
- workers.tf
> Remove invalid action from policy

- CHANGELOG.md
- examples/eks_test_fixture/main.tf
> Update eks module deps

- CHANGELOG.md
- local.tf
- workers_launch_template.tf
> Add option to use custom service linked role for Auto Scaling group

- CHANGELOG.md
- README.md
- outputs.tf
> Adding 2 new outputs: AMI ID and work user-data

- CHANGELOG.md
- local.tf
- workers.tf
- workers_launch_template.tf
- workers_launch_template_mixed.tf
Add option to change worker asg termination policy.
- [ X ] `terraform fmt` and `terraform validate` both work from the root and `examples/*` directories
- [ X ] CI tests are passing
- [ X ] I've added my change to CHANGELOG.md and highlighted any breaking changes
- [ X ] README.md has been updated after any changes to variables and outputs. See https://github.com/terraform-aws-modules/terraform-aws-eks/#doc-generation
> Termination Policy Option to worker ASG

- docs/spot-instances.md
> Remove outdated important issue links

- README.md
> Absolute URL in README to avoid 404 on terraform registry page

- README.md
> fix docs generation for lint

- .github/ISSUE_TEMPLATE.md
- README.md
- docs/faq.md
A FAQ was requested in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/522#issuecomment-534171988 and it makes sense. So here's a first draft.
> First FAQ draft

- docs/faq.md
Expand and clarify the networking section. Hopefully this helps some more. See #534
> FAQ: Expand and clarify the networking section.

- .pre-commit-config.yaml
> Add `terraform_validate` and `terraform_tflint` pre-commit hooks

- outputs.tf
Include OIDC output in TF 0.11
> Include OIDC output in TF 0.11

- .github/stale.yml
Will add the stale app https://github.com/apps/stale to close stale PR and issues.
> Add stale app

- CHANGELOG.md
- README.md
- cluster.tf
- variables.tf
- versions.tf
This adds support for setting the public endpoint CIDRs.
> Add public access endpoint CIDRs option (terraform-aws-eks#647)

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- modules/node_groups/README.md
> fix terraform pre-commit args for terraform-docs

- .pre-commit-config.yaml
- CHANGELOG.md
> bump pre-commit-terraform version

- CHANGELOG.md
- docs/faq.md
detailed algorithm for building EKS cluster with Windows nodes
Those changes are because of https://github.com/terraform-aws-modules/terraform-aws-eks/issues/717 . In other words we need more description how to do that.... I have provided it.
> Detailed description for enabling Windows nodes for AWS EKS

- local.tf
Follow-up PR after #761 failed as a result of encrypted key requiring a boolean
> 'root_encrypted' -> bool

- CHANGELOG.md
- README.md
This is not needed since 8.0.0 right?
> Remove assumption

- CHANGELOG.md
- irsa.tf
This is expanding conditional for irsa.tf to avoid failing plan during using `create_eks = false`
This is to fix https://github.com/terraform-aws-modules/terraform-aws-eks/issues/782
> change conditional for irsa.tf

- .chglog/config.yml
> fix: fix git-chglog configuration

- .chglog/config.yml
- CHANGELOG.md
@max-rocket-internet go for a new release ?
> skip changelog: Prepare for release 11.0.0

- .chglog/config.yml
- .github/CONTRIBUTING.md
- .github/semantic.yml
> chore: use chore semantic commits instead of skip changelog

- data.tf
- local.tf
> chore: move all locals in locals.tf

- docs/faq.md
A round of updates to the FAQ. Updating some history that no longer applies and add some of the recent issues.
Fixes: #885 
Fixes: #817 - maybe? There's a lot going on in that issue
> docs: Update FAQ

- CHANGELOG.md
> chore: update changelog for release 12.1.0

- CHANGELOG.md
> chore: update changelog for release 12.2.0

- .gitignore
- workers_launch_template.tf
Fix for https://github.com/terraform-aws-modules/terraform-aws-eks/issues/939
Add the lifecycle to the random_pet resource.
> fix: worker LT lifecycle problem

- .pre-commit-config.yaml
- README.md
> ci: Bump terraform pre-commit hook version and re-run terraform-docs with the latest version to fix the CI

- irsa.tf
- local.tf
This pull request updates the IRSA OIDC provider to use dynamic partition lookups to allow module usage for AWS-CN deployments.
> feat: Dynamic Partition for IRSA to support AWS-CN Deployments

- CHANGELOG.md
Prepare v13.0.0 release
Resolves: https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1025
> chore: update changelog for v13.0.0 release

- .github/workflows/lint.yml
Temporary fix for https://github.com/actions/virtual-environments/issues/1811
> ci: Fix GitHub Actions CI macOS build errors

- README.md
- outputs.tf
- variables.tf
Fixes https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1060
> fix: The type of the output `cloudwatch_log_group_name` should be a string and not a list of string

- examples/launch_templates_with_managed_node_groups/disk_encryption_policy.tf
- examples/launch_templates_with_managed_node_groups/launchtemplate.tf
- examples/launch_templates_with_managed_node_groups/main.tf
- examples/launch_templates_with_managed_node_groups/variables.tf
https://www.terraform.io/docs/configuration/syntax.html#comments
> chore: Use `#` for comments. It's the recommended way to start comment and it's more idiomatic

- CHANGELOG.md
> chore: Prepare for v13.1.0 release

- cluster.tf
- modules/fargate/data.tf
- workers.tf
- workers_launch_template.tf
> chore: fix linter for TF 0.14

- local.tf
- workers.tf
- workers_launch_template.tf
Adding the ability to define health-check type for autoscaling groups. I [saw this issue](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1009) without a PR, so this is that.
> feat: Add customizable Auto Scaling Group health check type

- modules/fargate/fargate.tf
- modules/fargate/locals.tf
…e tags for the fargate profile specifically
fix tags on fargate profile merging both the tags from cluster and the tags for the fargate profile specifically
> fix: Merge tags from Fargate profile with common tags from cluster

- examples/launch_templates_with_managed_node_groups/templates/userdata.sh.tpl
- templates/userdata.sh.tpl
> improvement: Dont set -x in userdata to avoid printing sensitive informations in logs

- CHANGELOG.md
> chore: Prepare for v14.0.0

- workers_launch_template.tf
> fix: Fixed list and map usage

- versions.tf
Resolves https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1332
> fix: Bump AWS provider version to add Warm Pool support

- README.md
- cluster.tf
- versions.tf
Add timeout of 5mn when waiting for cluster As the previous way had.
> feat: Add timeout of 5mn when waiting for cluster

- README.md
- data.tf
- examples/basic/main.tf
- examples/fargate/main.tf
- examples/instance_refresh/main.tf
- examples/irsa/main.tf
- examples/launch_templates/main.tf
- examples/launch_templates_with_managed_node_groups/main.tf
- examples/managed_node_groups/main.tf
- examples/secrets_encryption/main.tf
- examples/spot_instances/main.tf
- local.tf
- outputs.tf
This will add support to search for Windows (or Linux) AMI only if they are needed.
- Resolves #1100
- Resolves #1141
- Resolves #1246
- Resolves #1247
- Resolves #582
> feat: Search for Windows or Linux AMIs only if they are needed

- examples/bottlerocket/README.md
- examples/bottlerocket/data.tf
- examples/bottlerocket/main.tf
- examples/bottlerocket/userdata.toml
- examples/bottlerocket/variables.tf
There were a couple of PRs requesting changes to the module to run AWS Bottlerocket based nodes. (for example #840)
I got Bottlerocket up and running without any changes to the module so wanted to document it and possibly prevent
other PRs from trying to introduce changes that could be easily avoided.
> docs: Add Bottlerocket example

- LICENSE
- README.md
> docs: Update license to Apache 2 License

- modules/node_groups/README.md
- modules/node_groups/node_groups.tf
Allow to set ```force_update_version``` flag to managed node groups
> feat: Add ability to forcefully update nodes in managed node groups

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/changelog-check.yaml
- CHANGELOG.md
> chore: Remove CI tests from checklist in PR template

- .github/workflows/changelog-check.yaml
> chore: check for changelog only when CHANGELOG.md change

- .github/workflows/changelog-check.yaml
> chore: Check for changelog on `pull_request_target` only

- README.md
- cluster.tf
- variables.tf
> feat: Ability to tag just EKS cluster

- fargate.tf
> fix: Fixed coalescelist() with subnets in fargate module

- modules/node_groups/README.md
- modules/node_groups/launch_template.tf
- modules/node_groups/locals.tf
Add `metadata_options` in custom `launch_template` for managed node groups.
Useful for: https://docs.aws.amazon.com/eks/latest/userguide/best-practices-security.html
> feat: Add metadata_options for node_groups

- .github/stale.yml
Updating stale bot values to allow better and faster velocity of issues and PRs
> chore: Updated stalebot config

- docs/iam-permissions.md
we need the iam:TagPolicy for this module. I got error without this role
> docs: Updated iam-permissions.md

- docs/iam-permissions.md
We need to add TagInstanceProfile policy also, I got an error without this.
> docs: Update iam-permissions.md

- .pre-commit-config.yaml
> chore: Fixed CI (replaced git protocol with https)

- examples/launch_templates_with_managed_node_groups/main.tf
This is extending example about new feature introduced in recent PR, it will allow for better testing and give possibility to reference users into that example in `issues`
closes #1621
> chore: Extend example launch_templates_with_managed_node_groups

- docs/faq.md
Update FAQ about dedicated control plane subnet
Resolves #1312 #1620
> docs: update faq about dedicated subnets for control plane

- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .github/workflows/stale-actions.yaml
- Minor formatting to align with rest of repos
- Fix `release.yml` GitHub workflow to ensure release process does not run on forks; ref https://github.com/terraform-aws-modules/meta/issues/25
- Ensure organization configurations are aligned and standardized; most of these changes are copied from the current EKS repository
- No
- CI checks only
> chore: Update release configuration files to correctly use conventional-commits

- main.tf
The 2 lines in my proposed change were erroneously reversed in your original code.
> fix: Attributes in timeouts are erroneously reversed

- docs/UPGRADE-18.0.md
Provide a diff of before and after, making it easier to see differences.
Adding a diff visually showing the differences between v17 and v18
Adding a visual diff helps a lot seeing what changed between v17 and v18.
None
This is a text file change, no tests needed
> docs: Update UPGRADE-18.0.md and provide a diff between before (v17.x) and after (v18.x), making it easier to see differences.

- README.md
> docs: Update README to show KMS key ARN not ID

- examples/eks_managed_node_group/main.tf
Example for asg tagging to scale to 0 for managed node group doesn't work
In the asg taint tags example the tags generated are like this : 
```
key : k8s.io/cluster-autoscaler/node-template/taint/nameOfTheTaint
value: true:NO_SCHEDULE
```
But [cluster autoscaler](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup) requires another format : 
```
key : k8s.io/cluster-autoscaler/node-template/taint/nameOfTheTaint
value: true:NoSchedule
```
No
> chore: Correct example ASG tag(s) to match `cluster-autoscaler` requirements

- .pre-commit-config.yaml
- docs/faq.md
- Add section to FAQ about conflicting security group tags
- This is a common question asked by users that are not aware of the underlying pieces at play around security group tags and options to resolve for their use case
- Closes #2223
- Closes #2224
- Reference #1986
- No
> docs: Add section to FAQ about conflicting security group tags

- README.md
- docs/UPGRADE-19.0.md
- examples/eks_managed_node_group/README.md
- examples/eks_managed_node_group/main.tf
- examples/fargate_profile/main.tf
- examples/karpenter/main.tf
- main.tf
- modules/_user_data/main.tf
- node_groups.tf
- Correct spelling mistakes
- Resolves #2332 
- No
> docs: Correct spelling mistakes

- modules/eks-managed-node-group/main.tf
- modules/self-managed-node-group/main.tf
- Ensure all supported resources are tagged under `tag_specifications` on launch templates
- Reference https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_LaunchTemplateTagSpecificationRequest.html#API_LaunchTemplateTagSpecificationRequest_Contents
- Resolves #2351 
- No
> feat: Ensure all supported resources are tagged under `tag_specifications` on launch templates

- docs/compute_resources.md
Minimal update in documentation in order to align it to version 19.x.x.
I added a sentence on the implications of using custom launch template, which could have saved me quite some time, but feel free to close this PR if not necessary.
Just more ease of use I guess.
Changes do not affect existing code.
Changes do not affect existing code.
> docs: Update eks managed node group usage to v19

- examples/fargate_profile/main.tf
- Correct example where a list data type is required
- Missed this update from testing
- No
> chore: Correct example where a list data type is required

- CHANGELOG.md
Signed-off-by: Fernando Miguel <github@FernandoMiguel.net>
fix typos
> docs: Typos in MD

- docs/UPGRADE-19.0.md
Align the level of headings for Self Managed Node Groups and EKS Managed Node Groups.
> docs: Align level of headlines

- .pre-commit-config.yaml
- docs/UPGRADE-19.0.md
> docs: Update UPGRADE-19.0.md

- README.md
fix karpenter cfn link to IAM policy
link 404's as is
No
> docs: Correct Karpenter cfn link to IAM policy

- modules/eks-managed-node-group/main.tf
- modules/self-managed-node-group/main.tf
> fix: Updating license_specification result type

- README.md
- Fixed link to Upgrade to v20.x guide
> docs: Correct link for `UPGRADE-20.0.md` on main README

- docs/UPGRADE-20.0.md
the pr fixes a typo in the release note
reduce users confusion.
none
by comparison to code
> docs: Correct resolve conflicts argument in `UPGRADE-20.0.md`

- examples/karpenter/README.md
Spelling correction in README.md for Karpenter example.
Typo fix. Improves readability.
No
- [ * ] I have tested and validated these changes using one or more of the provided `examples/*` projects
> docs: Correct mis-spelling in README

- examples/karpenter/main.tf
> docs: Improve karpenter discovery tags example

- README.md
- examples/eks-managed-node-group/versions.tf
- examples/karpenter/README.md
- examples/karpenter/versions.tf
- examples/self-managed-node-group/versions.tf
- main.tf
- modules/eks-managed-node-group/README.md
- modules/eks-managed-node-group/versions.tf
- modules/fargate-profile/README.md
- modules/fargate-profile/versions.tf
- modules/karpenter/README.md
- modules/karpenter/versions.tf
- modules/self-managed-node-group/README.md
- modules/self-managed-node-group/versions.tf
- tests/eks-managed-node-group/README.md
- tests/eks-managed-node-group/main.tf
- tests/eks-managed-node-group/versions.tf
- tests/fargate-profile/README.md
- tests/fargate-profile/versions.tf
- tests/self-managed-node-group/README.md
- tests/self-managed-node-group/versions.tf
- variables.tf
- versions.tf
- Add support for zonal shift
- New feature from EKS
- Provider version 5.74 https://github.com/hashicorp/terraform-provider-aws/pull/39946
- No
> feat: Add support for zonal shift

- examples/eks-hybrid-nodes/README.md
> docs: Correct EKS Hybrid Nodes execution steps to apply successfully

- main.tf
- Correct Auto Mode disable
- Closes #3252 
- No
> fix: Correct Auto Mode disable

- main.tf
- Revert changes to disabling auto mode #3253
- Resolves #3254
- No
> fix: Revert changes to disabling auto mode #3253

- README.md
Add "Upgrade to v21.x"
Add "Upgrade to v21.x" in README.md
Link in README will be helpful for people, who want to upgrade to the latest v21.x version of module.
N/A
N/A
> docs: Add link to v21 upgrade guide in main `README.md`
